#!/bin/bash

# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../")

source "$M_ROOT/lib/functions.sh"
LOG="$M_ROOT/logs/block_ip.log"

if [ -e "$1" ] || [ "_$1" == "_-" ]; then
  ips=`cat $1 2>/dev/null | grep -v ^$ | sort | uniq`
fi

cleanup() {
$IPT -F M_IPBLOCK_TMP
$IPT -F M_IPBLOCK_CONST
$IPT -D INPUT -j M_IPBLOCK_TMP
$IPT -D INPUT -j M_IPBLOCK_CONST
$IPT -X M_IPBLOCK_TMP
$IPT -X M_IPBLOCK_CONST
}

[ -f "/sbin/iptables" ] && IPT=/sbin/iptables || IPT=`which iptables 2>/dev/null`
[ -z "$IPT" ] && echo "No iptables found" && exit 1

possible_options="method cleanup block_forever_after rate burst help"
necessary_options=""
[ -n "$ips" ] && shift
for s_option in $@
do
  found=0
  case $s_option in
  --*=*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'` 
    ;;
  --*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
    s_optarg='yes' 
    ;;
  *=*)
    echo "Wrong syntax: options must start with a double dash"
    exit 1
    ;;
  *)
    s_param="$s_option $s_param"
    s_optname=''
    s_optarg=''
    ;;
  esac
  for option in `echo $possible_options | sed 's/,//g'`; do 
    [ "_$s_optname" == "_$option" ] && eval "$option=$s_optarg" && found=1
  done
  [ "_$s_option" == "_$s_param" ] && found=1
  if [[ $found -ne 1 ]]; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done
found=0

if [ -n "$help" ]; then
  cat << "EOF"
Usage: $0 [ip list file] <options>

stdin can be used as well:

  echo "ip list" | $0 - <options>
  
Options:

  --help                            this help
  
  --block_forever_after=[N]         IPs are blocked temporarily by default,
                                    but every occasion is counted, and IP
                                    can be blocked forever after N temporary
                                    blocks; use N=0 to bypass temporary block
  
  --method=[method]                 is supposed to be either native iptables
                                    methods DROP and REJECT (default) that are
                                    simply converted to the string '-j [method]'
                                    or special method 'limit' which is converted
                                    to the string '-m limit --limit $rate 
                                    --limit-burst $burst -j ACCEPT'
                                    
  --rate=[rate]                     limit rate (see --method option and iptables
                                    documentation); default 1/s
  
  --burst=[burst]                   burst rate (see --method option and iptables
                                    documentation); default 5
                                    
  --cleanup                         purges all existing blocks and removes
                                    chains created by this script
                                    Note that it does not do anything with the
                                    blocked IPs lists $M_TEMP/ip_block.const
                                    and $M_TEMP/ip_block.tmp.

EOF

  exit 0
fi

source "$M_ROOT/conf/mon.conf"

[ -n "$cleanup" ] && cleanup && exit $?

[ -z "$BLOCK_CALLER" ] && BLOCK_CALLER="unknown"
[ -z "$method" ] && method=REJECT
if [ "$method" == "limit" ]; then
  [ -z "$rate" ] && rate="1/s"
  [ -z "$burst" ] && burst=5
  method="-m limit --limit $rate --limit-burst $burst -j ACCEPT"
else
  method="-j $method"
fi

$IPT -L M_IPBLOCK_CONST -n >/dev/null 2>&1
[ $? -eq 1 ] && $IPT -N M_IPBLOCK_CONST
[ `$IPT -L INPUT | grep -c ^M_IPBLOCK_CONST` -eq 0 ] && $IPT -I INPUT -j M_IPBLOCK_CONST

$IPT -L M_IPBLOCK_TMP -n >/dev/null 2>&1
if [ $? -eq 1 ] ; then
  $IPT -N M_IPBLOCK_TMP
else
  $IPT -F M_IPBLOCK_TMP
fi
[ `$IPT -L INPUT | grep -c ^M_IPBLOCK_TMP` -eq 0 ] && $IPT -I INPUT -j M_IPBLOCK_TMP

[ -z "$block_forever_after" ] && block_forever_after=99999
if [ -n "$ips" ] ; then
  for ip in $ips ; do
    ip=`echo "$ip" | tr -d ' '`
    # Never block own IPs! :)
    [[ `grep -c ^$ip\| "$M_ROOT/servers.list"` -ne 0 ]] && continue
    "$rpath"/localips | grep -q "^$ip$" && continue
    # If it is not an IP address, consequences are unpredictable
    expr "$ip" : ".*[^[0-9.:/]]*" >/dev/null && continue
    # Empty IP is even worse: everything gets blocked
    [ -z "$ip" ] && continue
    # Whitelist
    if [ -f "$M_ROOT/conf/ip.white.list" ]; then
      whitelisted=$(for wl in `cat "$M_ROOT/conf/ip.white.list"`; do expr "$ip" : ^$wl ; done | grep -v ^0$ | wc -l)
      [ $whitelisted -ne 0 ] && log "IP $ip is in white list" && continue
    fi
    echo "$ip|$BLOCK_CALLER" >> "$M_TEMP/ip_block.tmp"

    ipincl=`grep -c "^$ip|${BLOCK_CALLER}$" "$M_TEMP/ip_block.tmp"` || ipincl=0
    log "$ip :: logged: $ipincl times, forever after: $block_forever_after times"
    if [[ $ipincl -gt $block_forever_after ]] ; then
      if [[ `grep -c "^$ip|${BLOCK_CALLER}$" "$M_TEMP/ip_block.const"` -eq 0 ]] ; then
        echo "$ip|$BLOCK_CALLER" >> "$M_TEMP/ip_block.const"
        $IPT -A M_IPBLOCK_CONST -s $ip $method
        log "$ip blocked for ever by $BLOCK_CALLER"
      else
        log "$ip found in $M_TEMP/ip_block.const, check your firewall"
      fi
    else
      log "$ip :: blocking temporarily by $BLOCK_CALLER"
      $IPT -A M_IPBLOCK_TMP -s $ip $method
    fi

  done
fi


