#!/bin/bash

[ -z "$M_ROOT" ] && echo "M_ROOT is not defined" && exit 1
[ ! -d "$M_ROOT" ] && echo "M_ROOT does not exist" && exit 1

for f in $@ ; do
  if [ -f "$M_ROOT/$f" ]; then
    diff $M_ROOT/$f $M_ROOT/${f%.new}
  else
    diff $f ${f%.new}
  fi
done

