#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
#*/
M_ROOT=$(cd "$rpath/../" && pwd)

[ -d "$M_ROOT/rc" ] || install -d "$M_ROOT/rc"

if [ -z "$1" ]; then
initlist="connections services bandwidth disk cpu mem files servers cpu_eaters memory_eaters"

  declare -i i ; i=1
  for mon in $initlist ; do
    find "$M_ROOT/rc" -name "*\.${mon}.mon" -exec rm {} \;
    [[ `expr length $i` -eq 1 ]] && n="0$i" || n=$i
    ln -s "../tests/${mon}.mon" "$M_ROOT/rc/${n}.${mon}.mon"
    i+=1
  done

else
  if [ -f "$M_ROOT/tests/${1}" ] ; then
    mon=$1
  elif [ -f "$M_ROOT/tests/${1}.mon" ] ; then
    mon=${1}.mon
  else
    echo "Monitor $1 not found"
    exit 1
  fi
  if [ -n "$2" ]; then
    if [ `expr "$2" : ".*[^[0-9]]*"` -ne 0 ]; then
      echo "Usage: $rcommand [monitor name] <serial number>"
      exit 1
    else
      ln -s "../tests/${1}.mon" "$M_ROOT/rc/${2}.${1}.mon"
    fi
  else
    for rcmon in `find "$M_ROOT/rc" -maxdepth 1 -mindepth 1 -type l`; do
      sn=`echo "${rcmon##*/}" | cut -d'.' -f1`
      [[ $sn -gt $maxsn ]] && maxsn=$sn 
    done
    newsn=`expr $maxsn + 1`
    ln -s "../tests/${1}.mon" "$M_ROOT/rc/${2}.${1}.mon"
  fi

fi
