#!/bin/bash

# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rpath=$(readlink -f "$BASH_SOURCE")
rcommand=${rpath##*/}
rpath=${rpath%/*}
#*/

possible_options="file lines maxlines period interval timeformat help verbose resolution amendformat safetylimit"
necessary_options="file"
ARGV=`echo ${@} | sed 's/^--//' | sed 's/ --/|/g'`

amend() {
  amendcomm="echo \"$1\" | $amendformat"
  eval "$amendcomm"
}

IFS1=$IFS
IFS='|'
for s_option in $ARGV
do
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "X$s_optarg" == "X$s_optname" ] && s_optarg="yes"
  for option in `echo $possible_options | sed 's/ /|/g'`; do 
    [ "X$s_optname" == "X$option" ] && eval "$s_optname=\"$s_optarg\"" && found=1
  done
  if [[ $found -ne 1 ]]; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
  found=0
done
IFS=$IFS1

[ -n "$help" ] && echo -e "Possible options: $possible_options\nNecessary options: $necessary_options" && exit 0

[ -n "$verbose" ] && debug=true || debug=false

source "$rpath/../conf/mon.conf"
# defaults
[ -n "$interval" ] && period="$interval"
[ -z "$maxlines" ] && maxlines=1000
[ -z "$safetylimit" ] && safetylimit=50

if [ -n "$period" ]; then
  if ! expr "$period" : ".*[^[0-9]]*" >/dev/null ; then
    period="$period sec"
  fi
else
  period="$FREQ sec"
fi
[ -z "$timeformat" ] && timeformat='%b %e %H:%M'
if [ -n "$resolution" ]; then
  case $resolution in
    min|minute|minutes)
      res="1 min"
      ;;
    sec|second|seconds)
      res="1 sec"
      ;;
  esac
fi
if [ -z "$res" ]; then
  lastletter=`echo ${timeformat##*%} | cut -b 1`
  [ "X$lastletter" == "XM" ] && res="1 min"
  [ "X$lastletter" == "XS" ] && res="1 sec"
fi

$debug && echo "resolution: $res"

timepattern=`date -d "-${period}" +"$timeformat"`
timecurrent=`date +"$timeformat"`

$debug && echo "from: $timepattern to: $timecurrent"

ln=`tail -n $maxlines "$file" | grep -n -m 1 -h "$timepattern" | cut -d':' -f1`
if $debug ; then
  [ -z "$ln" ] && echo -e "Was unable to find the lines number, command was:\ntail -n $maxlines \"$file\" | grep -n -m 1 -h \"$timepattern\" | cut -d':' -f1"
else
  $debug && echo "lines number: $ln"
fi

if [ -n "$amendformat" ]; then
  timepattern=`amend "$timepattern"`
  timecurrent=`amend "$timecurrent"`
  $debug && echo "Amended: from: $timepattern to: $timecurrent"
fi

if [ -z "$ln" ] ; then
  $debug && echo "scanning the tail of the log with $res resolution"
  badpattern=false
  declare -i i ; i=0 ; ilimit=$safetylimit # safety limit
  while [[ "$timepattern" != "$timecurrent" ]]; do
    dd=`date -d "$timepattern" 2>/dev/null`
    if [ -z "$dd" ]; then
      $debug && echo -e "Empty date pattern, command was:\ndate -d \"$timepattern\""
      echo "Unable to restore date/time using pattern: $timepattern" >> "$rpath/../monitoring.log" && break
    else
      $debug && echo "$dd"
    fi
    timepattern=`date -d "$dd + $res" 2>/dev/null || badpattern=true`
    timepatternf=`date -d "$timepattern" +"$timeformat" 2>/dev/null || badpattern=true`
    i+=1
    $debug && echo "    $i :: $timepatternf"
    [ $i -gt $ilimit ] && break
    $badpattern && echo "Unable to restore date/time using pattern: $timepattern formatted as $timepatternf" >> "$rpath/../monitoring.log" && break
    ln=`tail -n $maxlines "$file" | grep -n -m 1 -h "$timepatternf" | cut -d':' -f1`
    $debug && echo "Datetime pattern: $timepattern Number of lines back: $ln"
    [[ $ln -gt 0 ]] && break
  done
fi

[[ $ln -gt 0 ]] && tail -n $maxlines "$file" | tail -n +$ln

exit 0



