#!/bin/bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


rcommand=${0##*/}
rpath=${0%/*}
#*/

LOSETUP=`which losetup 2>/dev/null`

[ -z "$LOSETUP" ] && echo "no losetup found" && exit 1
disk="$1"

map_disk0() {
  [ -z "$1" ] && log_error "argument to map_disk0 is empty" && return 1
  blockdev="$1"
  filesystem_dev_base=`kpartx -l -p- $blockdev | grep -m 1 -- "-1.*$blockdev" | awk '{print $1}'`
  if [ -z "$filesystem_dev_base" ]; then
    log_error "Cannot interpret kpartx output and get partition mapping using command:"
    log_error "kpartx -l -p- $blockdev | grep -m 1 -- \"-1.*$blockdev\" | awk '{print $1}'"
    exit 1
  fi
  kpartx -a -p- $blockdev > /dev/null
  filesystem_dev="/dev/mapper/$filesystem_dev_base"
  if [ ! -b "$filesystem_dev" ]; then
    `which dmsetup` mknodes
  fi
  if [ ! -b "$filesystem_dev" ]; then
    log_error "Can't find kpartx mapped partition: $filesystem_dev"
    exit 1
  fi
  echo "$filesystem_dev"
}

unmap_disk0() {
  kpartx -d -p- $1
}

if [ ! -b "$disk" ]; then
  blockdev=$($LOSETUP -f --show "$disk")
  CLEANUP+=("$LOSETUP -d $blockdev")
else
  blockdev="$disk"
fi

filesystem_dev=$(map_disk0 $blockdev)
CLEANUP+=("unmap_disk0 $blockdev")

TARGET=`mktemp -d` || exit 1
CLEANUP+=("rmdir $TARGET")

mount $filesystem_dev $TARGET || exit 1
CLEANUP+=("umount -l $TARGET")
CLEANUP+=("sync")

read -p "Now cd to $TARGET in another terminal. When finished, press Enter here to unmount the disk -> " theenter

cleanup
trap - EXIT

exit 0

