#!/bin/bash

rpath=$(readlink -f "$BASH_SOURCE")
rcommand=${rpath##*/}
rpath=${rpath%/*}
#*/

[ -z "$1" ] && echo "Usage: $rcommand testname" && exit 1

rm -f "${rpath}/../standalone/rc/"*".$1"
rm -f "${rpath}/../standalone/${1}/rc"/*

