#!/bin/bash
# Copyright (C) 2014 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(cd "$rpath/../" && pwd)

OSSL=`which openssl 2>/dev/null`
[ -z "$OSSL" ] && echo "openssl utility not found, exiting" && exit 1

possible_options="help verbose debug info url generate filename length days config username password"
[ -z "$*" ] && usage="yes"

IFSORIG=$IFS
IFS='-'
for s_option in "$@"
do
  found=false
  s_option=${s_option/--/}
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "_$s_optarg" == "_$s_optname" ] && s_optarg="yes"
  [ "_$s_optarg" == "_no" ] && unset $s_optname

  for option in ${possible_options// /-} ; do
    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
  done
  
  if ! $found ; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done
IFS=$IFSORIG

found=false
for option in $necessary_options ; do
  [ -z "$(eval echo \$$option)" ] && missing_options="$missing_options --${option}," && found=true
done
if $found ; then
  echo "Necessary options: ${missing_options/%,/} not found"
  exit 1
fi

[ -n "$config" ] && CONFIG="-config $config" || CONFIG="-config $rpath/${rcommand}.conf"

generate_htpasswd() {
  $OSSL passwd -crypt $1
}

generate_selfsigned() {
  $OSSL req -x509 -nodes -newkey rsa:${length} -keyout ${filename%.*}.key -out $filename -days $days $CONFIG
}

generate_ca() {
  $OSSL req -new -x509 -extensions v3_ca -keyout ${filename%.*}-ca.key -out ${filename%.*}-ca.pem -days $days $CONFIG
}

generate_csr() {
  $OSSL req -new -nodes -out ${filename%.*}.csr -newkey rsa:${length} -keyout ${filename%.*}.key $CONFIG
}

generate_signed() {
  #$OSSL x509 -req -in ${filename%.*}.csr -CA ${filename%.*}-ca.pem -CAkey ${filename%.*}-ca.key -CAcreateserial -out $filename -days $days
  touch serial index.txt
  $OSSL ca -in ${filename%.*}.csr -out $filename -cert ${filename%.*}-ca.pem -keyfile ${filename%.*}-ca.key -days $days $CONFIG
  rm serial index.txt
}

read_csr() {
  [ -z "$filename" ] && echo "Option --filename is mandatory" && exit 1
  [ -e "$filename" ] && echo "File $filename not found" && exit 1
  [ -n "$url" ] && echo "Option --url is ignored"
  $OSSL req -in $filename -noout -text
}

cert_summary() {
  if [ -n "$filename" ]; then
    $OSSL x509 -in $filename -noout -text
  fi
}

[ -n "$help" ] && usage="yes"

if [ -n "$usage" ]; then
  echo -e "Usage: $rcommand <long-options>\n\n    Options:\n\n      --generate=[type]\t\tgenerates a x509 certificate, the only supported type for now is \"self-signed\"\n\n      --days=[n]\t\t\tperiod of certificate validity in days\n\n      --filename=[path/to/file]\t\tname of the file the new certificate will be saved as\n\n      --verbose\t\t\tshow some additional info\n\n      --help\t\t\tthis help"
  exit 0
fi

if [ -n "$generate" ]; then
  [ -n "$info" ] && echo "Option 'info' and 'generate' can't go together" && exit 1

  case $generate in
    ss|self-signed|selfsigned)
      [ -z "$days" ] && days=365
      [ -z "$length" ] && length=2048
      expr $days : "^[0-9]*$" 2>/dev/null || exit 1
      expr $length : "^[0-9]*$" 2>/dev/null || exit 1
      [ -z "$filename" ] && filename="server.crt"
      generate_selfsigned
      ;;
    csr|request)
      [ -z "$length" ] && length=2048
      [ -z "$filename" ] && filename="server.csr"
      generate_csr
      ;;
    chain)
      [ -z "$days" ] && days=365
      [ -z "$length" ] && length=2048
      expr $days : "^[0-9]*$" 2>/dev/null || exit 1
      expr $length : "^[0-9]*$" 2>/dev/null || exit 1
      [ -z "$filename" ] && filename="server.pem"
      generate_ca
      generate_csr
      generate_signed
      ;;
    htpasswd)
      [ -z "$filename" ] && filename="htpasswd"
      echo "${username}:`generate_htpasswd $password`" >> $filename
      ;;
    *)
      echo "generation of $generate is not supported yet"
      ;;
  esac
fi

if [ -n "$info" ]; then
  [ -n "$generate" ] && echo "Option 'info' and 'generate' can't be used together" && exit 1
  case $info in
    req|csr|CSR)
      read_csr
      ;;
    x509|cert|certificate)
      cert_summary
      ;;
    rsa|key)
      test_key
      ;;
    *)
      echo "info=$info not supported"
      ;;
  esac
fi





