#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../")
#*/

for f in $@ ; do
  if [ "${f##*.}" == "new" ]; then
    if [ "${f:0:1}" == "/" ]; then
      [ -f "$f" ] || continue
      mv "$f" "${f%.new}"
    else
      [ -f "$M_ROOT/$f" ] || continue
      mv $M_ROOT/$f $M_ROOT/${f%.new}
    fi
  fi
done

