#!/bin/bash
# Copyright (C) 2014 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(cd "$rpath/../" && pwd)

a=`head -3 "$1" | tail -1`
b=`expr "$a" : "[[:space:]]*\([0-9]*\)[[:space:]]"`

today=`date +"%Y%m%d"`

fileday=`echo "$b" | cut -b -8`
fileserial=`echo "$b" | cut -b 9-`

if [ "_$fileday" == "_$today" ]; then
  serial=`expr $fileserial + 1 2>/dev/null`
  expr $serial : "^[0-9]*$" >/dev/null || exit 1
  [ `echo -n $serial | wc -m` -eq 1 ] && serial="0${serial}"
else
  serial="01"
fi

sed -i "/${fileday}${fileserial}/s/${fileday}${fileserial}/${today}${serial}/" "$1"
