#!/bin/bash

M_ROOT="$PWD/../.."
source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/lib/dash_functions.sh"
source "$M_ROOT/lib/cloud_functions.sh"
source "$M_ROOT/standalone/Postfix/postfix_queue.conf"

if [ "_$2" == "_localhost" ]; then
  target=localhost
else
  ip="$2"
  if "$M_ROOT"/helpers/localips | grep -q "^`name_to_ip "$ip"`$" ; then
    unset ip
    target=localhost
  else
    target=$ip
  fi
fi
for qtype in $GRAPHS_FOR ; do
  publish_graph `"$M_ROOT"/graph --database=standalone/Postfix/postfix_queue.db --table=postfix_queue --metric=qlength --as=$qtype --where="qtype:$qtype" --ip=$ip --perpixel --width=750 --height=300 --padding=10 --legend=160 2>&1`
done
