#!/usr/bin/env bash
# Copyright (C) 2008-2009 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

addxmarks() {
  marksX="$marksX`echo "<line x1=\\"$1\\" y1=\\"$mX1\\" x2=\\"$1\\" y2=\\"$mX2\\" />"`"
  textX="${textX}`echo "<text x=\\"$1\\" y=\\"$mXT1\\" >$2</text>"`"
}

addxlongmark() {
  coord="$1"
  shift
  marksX="$marksX`echo "<line x1=\\"$coord\\" y1=\\"$mXL\\" x2=\\"$coord\\" y2=\\"$startY\\" />"`"
  #textX="${textX}`echo "<text x=\\"$coord\\" y=\\"$mXLT\\" transform=\\"rotate(90,${coord},${mXLT})\\">$@</text>"`"
  textX="${textX}`echo "<text x=\\"$coord\\" y=\\"$mXLT\\" >$@</text>"`"
}

rpath=$(readlink -f "$BASH_SOURCE")
rcommand=${rpath##*/}
rpath=${rpath%/*}
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath")
#*/

# to enable debug logging even without command-line option
debug=true

[ -n "$CLOUD" ] && source "$rpath/conf/clouds/${CLOUD}.conf"
[ -n "$SSHPORT" ] || SSHPORT=22

IFCFG=`which ifconfig 2>/dev/null`
possible_options="metric help from to ip database table size width height scale padding legend fontsize strokewidth pointsize where as legendpos perpixel debug min"
necessary_options="metric"
source "$rpath/conf/mon.conf"
source "$rpath/conf/dash.conf"
source "$rpath/lib/functions.sh"

LOG="$rpath/logs/dashboard.log"

SSH=`which ssh 2>/dev/null`
[ -z "$SSH" ] && log "No ssh found" && exit 1

if [ -z "$freqdef" ]; then
  timeshift=`cat "$M_TEMP/timeshift" 2>/dev/null`
  [ -z "$timeshift" ] && timeshift=5
  freqdef=$(($FREQ + $timeshift))
fi
RSYNC=`which rsync 2>/dev/null`
SQL3=`which sqlite3 2>/dev/null` # assuming that remote path is the same

for s_option in "$@"
do
  found=0
  case $s_option in
  --*=*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'` 
    ;;
  --*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
    s_optarg='yes' 
    ;;
  *=*)
    log "Wrong syntax: options must start with a double dash"
    exit 1
    ;;
  *)
    s_param=$s_option
    s_optname=''
    s_optarg=''
    ;;
  esac
  for option in `echo $possible_options | sed 's/,//g'`; do 
    [ "X$s_optname" == "X$option" ] && eval "$option=$s_optarg" && found=1
  done
  [ "X$s_option" == "X$s_param" ] && found=1
  if [[ $found -ne 1 ]]; then 
    log "Unknown option: $s_optname"
    exit 1
  fi
done
# "metric help from to ip new database table size width height scale padding legend fontsize strokewidth pointsize"
if [ "X$help" == "Xyes" ] ; then
cat << "EOF"
Usage: ${0##*/} --metric=metric <other options>

Without --from a graph for the default period will be generated,
depending on the graph size and FREQ variable (see conf/dash.conf).
The --to option is ignored in this case.
With --from but without --to the latter defaults to the current time.

Options:

--ip=<IP>               IP address of the server to get data from
                        Server must be present in servers.list
                        If empty, means localhost
                    
--from=<date/time>      time of the beginning of the graph in any format
                        acceptable by the 'date' utility

--to=<date/time>        graph end time in any format acceptable by the 'date'
                        utility

--metric=<metric>       metric = database field name
                        Multiple metrics accepted, separated by comma, no spaces
                  
--database=<path/to/database>
                        path to database file, relative to M-Script root folder
                        The default is sysdata
                    
--table=<table name>    The default is sysdata

--size=<small|thumbnail>
                        If not defined, it's the default big graph
                        
--scale                 Used to create combined graphs with multiple metrics.
                        Makes exact values useless. Good only to see relative
                        changes of various metrics.
                        
--where=<field:value>   Additional WHERE clause for SQL query.
                        
--as=<name>             New name for metric. Especially useful if metric is an
                        ariphmetic expression like:
                        --metric=\"\(metric1+metric2\)\" --as=MyMetric
                        
--perpixel              Renders one value per pixel along X-Axis thus saving
                        CPU cycles
                        
--legendpos=<left|below>

Graph format options:

  --width, --height, --padding, --legend,           These options can be used
  --fontsize, --strokewidth, --pointsize            to overwrites those from
                                                    conf/dash.conf.
  
  
EOF
  exit 0
fi
found=0

for option in `echo $necessary_options | sed 's/,//g'`; do
  [ "X$(eval echo \$$option)" == "X" ] && missing_options="${missing_options}, --${option}" && found=1
done
if [[ found -eq 1 ]]; then
  missing_options=${missing_options#*,}
  log "Necessary options: $missing_options not found"
  exit 1
fi

[ -z "$debug" ] && debug=false || debug=true

[ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//'`
if [ -n "$ip" ] ; then
  if [ `echo $ip | grep -c "^$localip$"` -ne 0 ] ; then
    localip="yes"
  else
    unset localip
  fi
else
  localip="yes"
fi

M_TEMP="$M_TEMP"/dash
install -d "$M_TEMP"
install -d "$rpath/www/graphs"
declare -a colors
colors=( "#009900" "#000099" "#999900" "#660000" "#990099" "#009999" "#666600" "#44ff00" "#4400ff" "#00ff44" "#996644" "#994466" "#446699" "#449966" "#664499" "#669944" )

##################################
#### Definitions and defaults ####
##################################

[ -n "$padding" ] || padding=20
[ -n "$axis" ] || axis=40
[ -n "$legend" ] || legend=60
[ -n "$fontsize" ] || fontsize=10
[ -n "$strokewidth" ] || strokewidth=2
[ -n "$pointsize" ] || pointsize=12
[ -n "$width" ] && graphH=$width
[ -n "$height" ] && graphV=$height
[ -n "$graphH" ] && [ -n "$graphV" ] || (log "Define graph size in conf/dash.conf or as command-line options" && exit 1)
if [ "X$size" == "Xsmall" ] ; then
  graphH=`expr $graphH / 2`
  graphV=`expr $graphV / 2`
  padding=`expr $padding / 2`
  axis=`expr $axis / 2`
  legend=`expr $legend / 2`
  fontsize=`expr $fontsize - 2`
  strokewidth=1
  pointsize=`expr $pointsize / 2`
fi
if [ "Xsize" == "Xthumbnail" ] ; then
  graphH=`expr $graphH / 4`
  graphV=`expr $graphV / 4`
  padding=`expr $padding / 4`
  axis=`expr $axis / 4`
  legend=`expr $legend / 4`
  fontsize=`expr $fontsize - 4`
  strokewidth=1
  pointsize=`expr $pointsize / 4`
fi
[ "X$min" == "Xauto" ] && minauto=true || minauto=false
[ -z "$legendpos" ] && legendpos=left
[ "$legendpos" == "left" ] && legendH=$legend && legendV=0
[ "$legendpos" == "below" ] && legendH=0 && legendV=$legend
areaH=`expr $graphH - 2 \* $padding - $legendH - $axis`
areaV=`expr $graphV - 2 \* $padding - $legendV - $axis`

#####################
#### Time period ####
#####################

# perpixel option makes time period obsolete
if [ -z "$perpixel" ] ; then
  # the idea is to work entirely in UTC (timestamps in the db is UTC as well)
  # only X axis marks are converted to server local time
  if [ -n "$from" ] ; then
  # whatever you provide as --from, it is supposed to be UTC unless you provided
  # the time zone. In this latter case it will be converted to UTC, not just
  # considered to be UTC
    tfrom=`date -u -d "$from"`
    from=`date -u -d "$from" +"%s"`
    if [ -n "$to" ] ; then
      tto=`date -u -d "$to"`
      to=`date -d "$to" +"%s"`
    else
      to=`date +"%s"`
      tto=`date -u`
    fi
  else
    from=`date +"%s"` # this is always UTC
    from=`expr $from - $areaH \* $freqdef`
    tfrom=`date -u -d "1970/01/01 +$from sec"`
    to=`date +"%s"`
    tto=`date -u`
  fi
  title="Graph: $metric from $tfrom to $tto"
  #tlength=`expr length $title`
  log "Generating graph $metric from $tfrom to $tto"
else
  title="Graph: $metric"
  log "Generating graph ${metric}, last $areaH values"
fi

##############################
#### Servers and clusters ####
##############################

if [ -z "$localip" ] ; then
  server=`grep "^${ip}|" "$rpath/servers.list"|tail -1`
  if [ -z "$server" ] ; then
    log "Server with IP $ip not found in $rpath/servers.list"
    exit 1
  fi
  sIP=`echo $server | cut -d'|' -f1`
  skey=`echo $server | cut -d'|' -f2`
  scluster=`echo $server | cut -d'|' -f5`
  mpath=`cat "$rpath/conf/clusters.conf"|grep "^${scluster}|"|tail -1|cut -d'|' -f8`
  [ -z "$mpath" ] && log "M-Script path for server $server not found" && exit 1
  [ -f "$rpath/keys/$skey" ] && thekey="-i $rpath/keys/$skey"
  [ -z "$thekey" -a -f "$rpath/keys/${skey}.pem" ] && thekey="-i $rpath/keys/${skey}.pem"
  [ -z "$SSH_REMOTE_USER" ] && SSH_REMOTE_USER=`cat "$rpath/conf/clusters.conf"|grep "^${scluster}|"|tail -1|cut -s -d'|' -f13`
  [ -z "$SSH_REMOTE_USER" ] && SSH_REMOTE_USER="root"
  $debug && log "fetching data from ${sIP}, cluster $scluster using key $skey"
else
  sIP="localhost"
  $debug && log "reading data from localhost"
fi

###########################
#### Querying the data ####
###########################

[ -z "$database" ] && database="sysdata"
dbname=`echo "$database" | tr '/' '_'`
[ -z "$table" ] && table="sysdata" || dbname="${dbname}_${table}"
[ -n "$where" ] && dbname="${dbname}_`echo "$where" | tr -d \\ | tr -d \' | tr ':' '_' | tr ' ' '_'`"
  if [ -n "$as" ] ; then
    name=$as
  else 
    name=`echo $metric | tr ',' '_'`
  fi

if [ -n "$perpixel" ]; then
  $debug && log "per pixel mode"
  expr $perpixel / 1 >/dev/null 2>&1 || perpixel=1
  limit=$(($areaH/$perpixel))
###### Getting min and max values from database
  if [ `expr $metric : .*,` -eq 0 ] ; then
    $minauto && minQ="min($metric)"
    maxQ="max($metric)"
  else
    for smetric in `echo $metric | tr ',' ' '` ; do
      $minauto && minQ="${minQ}min($smetric),"
      maxQ="${maxQ}max($smetric),"
    done
    $minauto && minQ="${minQ%,}"
    maxQ="${maxQ%,}"
  fi
  nonempty=`echo $metric | sed "s|,|\<\>'' and |g"`
  nonempty="${nonempty}<>''"
  if [ -n "$where" ] ; then
    field=${where%%:*}
    value=${where#*:}
    $minauto && minQ="select $minQ from (select $metric from $table where $nonempty and  $field='$value' order by timeindex desc limit $limit)"
    maxQ="select $maxQ from (select $metric from $table where $nonempty and $field='$value' order by timeindex desc limit $limit)"
  else
    $minauto && minQ="select $minQ from (select $metric from $table where $nonempty order by timeindex desc limit $limit)"
    maxQ="select $maxQ from (select $metric from $table where $nonempty order by timeindex desc limit $limit)"
  fi
  $debug && log "$maxQ"
  if [ "$sIP" == "localhost" ]; then
    $minauto && minres=`$SQL3 "$rpath/$database" "$minQ"`
    maxres=`$SQL3 "$rpath/$database" "$maxQ"`
  else
    minmax=`$SSH $thekey -p $SSHPORT "$SSH_REMOTE_USER"@"$sIP" "$SQL3 \"$mpath/$database\" \"$maxQ ; $minQ\""`
    maxres=`echo "$minmax" | head -1`
    $minauto && minres=`echo "$minmax" | tail -1`
  fi
  [ -z "$maxres" ] && log "Was unable to find the maximum, exiting" && exit 1

  Nmax=0
  Nmin=0
  if $minauto ; then
    metricminfp=$(echo $minres | tr '|' '\n' | while read N ; do [ `solve 2 "$N < $Nmin"` -eq 1 ] && Nmin=$N ; echo $Nmin; done | tail -1) ; metricmin=${metricminfp%.*}
  else
    metricminfp=0
    metricmin=0
  fi
  metricmaxfp=$(echo $maxres | tr '|' '\n' | while read N ; do [ `solve 2 "$N > $Nmax"` -eq 1 ] && Nmax=$N ; echo $Nmax; done | tail -1) ; metricmax=${metricmaxfp%.*} ; metricmax=`expr $metricmax + 1`
  $debug && log "metricmaxfp: $metricmaxfp  metricmax: $metricmax"

  if [ -z "$metricminfp" -o -z "$metricmaxfp" ] ; then
    log "Error getting minimum and maximum values for $metric $limit last values"
    exit 1
  fi
  [ -z "$metricmin" ] && metricmin=0
  [ -z "$metricmax" ] && metricmax=$areaV
  mp=`solve 2 "$areaV / $metricmax"`

  $debug && log "mp: $mp"

  if [ `solve 2 "$mp > 0"` -eq 0 ] ; then
  # 1mln is a reasonable limit (scale 2 x 3); make i<=3 to make it a billion
    for ((i=1; i<=2; i++)); do
      [ `solve 2 "$mp > 0"` -eq 0 ] && mp=`echo "scale=($i * 3); $areaV / $metricmax" | bc`
      $debug && log "mp: $mp"
    done
  fi

  mpl=${mp%%.*}
  [ "X$mpl" == "X" ] && mpl=0
  if [[ $mpl -eq 0 ]]; then
    ll=${mp##*.}
    ll=`expr $ll : 0*`
    mpl="-$ll"
  else
    mpl=${#mpl}
    ll=0
  fi
  mpl=`expr $mpl - 2`
  d=`echo "scale=$ll+2; 10 ^ $mpl" | bc`
log "d=$d"
  bs=`echo "$mp / $d" | bc`
  if [ `expr $bs \< 20` -eq 1 ]; then
    mpr=10
  elif [ `expr $bs \< 50` -eq 1 ]; then
    mpr=20
  elif [ `expr $bs \< 100` -eq 1 ]; then
    mpr=50
  else
    mpr=100
  fi
  mp=`echo "$mpr * $d" | bc`
  $debug && log "mp: $mp"
  metricmax=`solve 2 "$areaV / $mp"`
  metricmax=${metricmax%%.*}
  to=`date +"%s"`
  $debug && log "min value: $metricmin  max value: $metricmax  vertical size: $areaV  coeff: $mp"
  if [ `expr $metric : .*,` -eq 0 ] ; then
    metricQ="${metric}*${mp}"
  else
    for smetric in `echo $metric | tr ',' ' '` ; do
      metricQ="${metricQ}${smetric}*${mp},"
    done
    metricQ="${metricQ%,}"
  fi
  if [ -n "$where" ] ; then
    QUERY="select $metricQ from $table WHERE $field='$value' order by timeindex desc limit $limit"
    QUERYFROM="select timeindex from $table WHERE $field='$value' order by timeindex desc limit $limit"
  else
    QUERYFROM="select timeindex from $table order by timeindex desc limit $limit"
    QUERY="select $metricQ from $table order by timeindex desc limit $limit"
  fi
  $debug && log "$QUERY"
  if [ "$sIP" == "localhost" ]; then
    $SQL3 "$rpath/$database" "$QUERY" > "$M_TEMP/graph.${sIP}.${dbname}.${name}"
    from=`$SQL3 "$rpath/$database" "$QUERYFROM" | tail -1`
  else
    $debug && log "$SSH $thekey -p $SSHPORT "$SSH_REMOTE_USER"@"$sIP" $SQL3 \"${mpath}/$database\" \"${QUERY}\""
    $SSH $thekey -p $SSHPORT "$SSH_REMOTE_USER"@"$sIP" "$SQL3 \"$mpath/$database\" \"$QUERY\"" > $M_TEMP/graph.${sIP}.${dbname}.${name}
    from=`$SSH $thekey -p $SSHPORT "$SSH_REMOTE_USER"@"$sIP" "$SQL3 \"$mpath/$database\" \"$QUERYFROM\"" \| tail -1`
  fi
  log "from: $from  to: $to"
  if [ `cat "$M_TEMP/graph.${sIP}.${dbname}.${name}" | wc -l` -le 5 ] ; then
    log "Too few data for graph or connection to $sIP problem. Graph is not generated."
    exit 1
  fi
  sn=`echo $metric | tr ',' ' ' | wc -w`

######## non-perpixel
else
  $debug && log "scaled mode (per pixel mode disabled)"
  metricmin=0
  metricmax=0
  # Using fixed multiplyer to avoid double querying
  mp=100
  qmetric="timeindex"
  for smetric in `echo $metric | tr ',' ' '` ; do
    rm -f "$M_TEMP/graph.${sIP}.${dbname}.${smetric}" 2>/dev/null
    qmetric="${qmetric}, ${smetric}*${mp}"
  done
    
  QUERY="SELECT $qmetric FROM $table WHERE timeindex BETWEEN $from AND $to"
  if [ -n "$where" ] ; then
    field=${where%%:*}
    value=${where#*:}
    QUERY="$QUERY AND $field='$value'" 
  fi
  if [ "X$sIP" == "Xlocalhost" ] ; then
    $debug && log "$SQL3 \"$rpath/$database\" \"$QUERY\""
    $SQL3 "$rpath/$database" "$QUERY" > "$M_TEMP/graph.${sIP}.${dbname}.${name}" || log "Problem getting $smetric data from $rpath/${database}, server $sIP"
  else
  # -o StrictHostKeyChecking=no
    $debug && log "$SSH $thekey -p $SSHPORT "$SSH_REMOTE_USER"@"$sIP" $SQL3 \"$mpath/$database\" \"$QUERY\""
    $SSH $thekey -p $SSHPORT "$SSH_REMOTE_USER"@"$sIP" "$SQL3 \"$mpath/$database\" \"$QUERY\"" > "$M_TEMP/graph.${sIP}.${dbname}.${name}" || log "Problem getting data from $rpath/${database}, server $sIP"
  fi
  if [ `cat "$M_TEMP/graph.${sIP}.${dbname}.${name}" | wc -l` -le 1 ] ; then
    log "Too little data for graph. Might be connection to $sIP problems. Graph is not generated."
    exit 1
  fi

#############################
#### Processing the data ####
#############################

  declare -i n
  n=2
  for smetric in `echo $metric | tr ',' ' '` ; do
    smax=`cat "$M_TEMP/graph.${sIP}.${dbname}.${name}" | cut -d'|' -f${n} | sort -n | tail -1` ; smax=${smax%.*}
    smin=`cat "$M_TEMP/graph.${sIP}.${dbname}.${name}" | cut -d'|' -f${n} | grep -v ^$ | sort -n | head -1` ; smin=${smin%.*}
    [[ $metricmax -eq 0 ]] && metricmin=$smax
    [ -z "$metricmin" ] && metricmin=0
    [[ $smax -gt $metricmax ]] && metricmax=$smax
    [[ $smin -lt $metricmin ]] && metricmin=$smin
    n+=1
  done
  sn=`echo $metric | tr ',' ' ' | wc -w`

  if [ "X$scale" == "Xyes" ] ; then
    sadd=`solve 2 "($metricmax - $metricmin) / $sn"` 2>/dev/null || sadd=`solve 2 "$metricmax / $sn"` 2>/dev/null || sadd=10
    snadd=0
    n=2
    for smetric in `echo $metric | tr ',' ' '` ; do
      rm -f "$M_TEMP/graph.${sIP}.${dbname}.${smetric}.scaled" 2>/dev/null
      smax=`cat "$M_TEMP/graph.${sIP}.${dbname}.${name}" | cut -d'|' -f${n} | sort -n | tail -1`
      if [ -n "$smax" ] ; then
        [ `echo "$smax == 0" | bc` -ne 1 ] && sratio=`solve 2 "$metricmax / $smax / $sn / 1.2"` || sratio=1
        for LINE in `cat "$M_TEMP/graph.${sIP}.${dbname}.${name}" | cut -d'|' -f1,${n}` ; do
          st=`echo $LINE | cut -d'|' -f1`
          [ -z "$st" ] && continue
          sd=`echo $LINE | cut -d'|' -f2`
          [ -z "$sd" ] && continue
          sds=`solve 2 "$sd * $sratio + $snadd"`
          echo "$st|$sds" >> $M_TEMP/graph.${sIP}.${dbname}.${smetric}.scaled
        done
      fi
      snadd=`solve 2 "$snadd + $sadd"`
      n+=1
    done
  fi

fi #### perpixel or not condition end

#####################################
#### Graph geometry calculations ####
#####################################

# 20 to 40 pixels
countminX=20
countminY=20

# needed for both perpixel and non-perpixel modes
perdotY=`expr 100 \* \( $metricmax - $metricmin \) / $areaV`
[ $perdotY -eq 0 ] && perdotY=1
perdotX=`expr \( $to - $from \) / $areaH`
[ $perdotX -eq 0 ] && perdotX=1

# How many pixels one hour takes
hourX=`expr 3600 / $perdotX`
[[ $hourX -lt 1 ]] && hourX=1
# Variable looping across all X marks
currpoint=$from
# Various coordinates
# 0:0 coordinate
startX=`expr $legendH + $padding + $axis`
startY=`expr $graphV - $legendV - $padding - $axis`
# Vertical grid lines
mX1=`expr $startY + 5`
mXT1=`expr $mX1 + 14`
mX2=$padding
mXL=`expr $startY + 18`
mXLT=`expr $startY + 32`
# Horisontal grid lines
mY1=`expr $startX - 5`
mYT1=`expr $mY1 - 50`
mY2=`expr $graphH - $padding`
# Axis names coordinates
axisXX=`expr $graphH - $padding - 60`
axisXY=`expr $graphV - $legendV - $axis + 20`
axisYX=$padding
axisYY=$padding

#titleX=`expr \( $graphH - $tlength \) / 2`
titleX=`expr $padding + $legendH + 20`
titleY=`expr $graphV - \( $padding / 2 \)`

########  Here begins the X-Axis marks definition part

if [[ $hourX -lt $countminX ]] ; then
  # 1-hour marks would be too close to each other
  # How many hours are within 40 pixels
  hourN=`expr 2 \* $countminX / $hourX`
  # If it's more than 24 hours, try days instead:
  if [[ $hourN -ge 24 ]] ; then
    #echo "Trying days"
    # How many pixels 1 day takes
    dayX=`expr 86400 / $perdotX`
    [[ $dayX -lt 1 ]] && dayX=1
    if [[ $dayX -lt $countminX ]] ; then
      # How many days are within 40 pixels
      dayN=`expr 2 \* $countminX / $dayX`
      # If it's more than 30 days, use months instead:
      if [[ $dayN -ge 30 ]] ; then
        # How many pixels are there in one month
        monthX=`expr 2592000 / $perdotX`
        [[ $monthX -lt 1 ]] && monthX=1
        if [[ $monthX -lt $countminX ]] ; then
        # Resolution should be this many months
          res=`expr 2 \* $countminX / $monthX`
        else
          res=1
        fi
        axisX="months"
        # Finding the next month beginning
        while [[ $currpoint -lt $to ]]
        do
          currpoint=`date -u -d "1970/01/01 +$currpoint sec +$res month" +"%s"`
          themonth=`date -u -d "1970/01/01 +$currpoint sec" +"%m"`
          theyear=`date -u -d "1970/01/01 +$currpoint sec" +"%Y"`
          themark=`date -u -d "$theyear/$themonth/1" +"%s"`
          themark=`expr \( $themark - $from \) / $perdotX + $startX`
          [[ $themark -gt $mY2 ]] && break
          textmark=`date -u -d "1970/01/01 +$currpoint sec"`
          textmark=`date -d "$textmark" +"%m"`
          addxmarks ${themark}.5 $textmark
        done
        unset nextmonth res monthX
      else
        #echo "Using days"
        axisX="days"
        [[ $dayN -eq 0 ]] && dayN=1  # just in case
        while [[ $currpoint -lt $to ]]
        do
          currpoint=`date -u -d "1970/01/01 +$currpoint sec +$dayN day" +"%s"`
          theday=`date -u -d "1970/01/01 +$currpoint sec" +"%d"`
          themonth=`date -u -d "1970/01/01 +$currpoint sec" +"%m"`
          theyear=`date -u -d "1970/01/01 +$currpoint sec" +"%Y"`
          themark=`date -u -d "${theyear}/${themonth}/${theday} 00:00" +"%s"`
          themark=`expr \( $themark - $from \) / $perdotX + $startX`
          [[ $themark -gt $mY2 ]] && break
          textmark=`date -u -d "1970/01/01 +$currpoint sec"`
          textmark=`date -d "$textmark" +"%d"`
          addxmarks ${themark}.5 $textmark
        done
        unset nextday
      fi
    else
      dayN=1
      axisX="days"
      while [[ $currpoint -lt $to ]]
      do
        currpoint=`date -u -d "1970/01/01 +$currpoint sec +$dayN day" +"%s"`
        theday=`date -u -d "1970/01/01 +$currpoint sec" +"%d"`
        themonth=`date -u -d "1970/01/01 +$currpoint sec" +"%m"`
        theyear=`date -u -d "1970/01/01 +$currpoint sec" +"%Y"`
        themark=`date -u -d "${theyear}/${themonth}/${theday} 00:00" +"%s"`
        themark=`expr \( $themark - $from \) / $perdotX + $startX`
        [[ $themark -gt $mY2 ]] && break
        textmark=`date -u -d "1970/01/01 +$currpoint sec"`
        textmark=`date -d "$textmark" +"%d"`
        addxmarks ${themark}.5 $textmark
      done
    fi
    unset dayN
  else
    axisX="hours"
    [[ $hourN -eq 0 ]] && hourN=1
    while [[ $currpoint -lt $to ]]
    do
      currpoint=`date -u -d "1970/01/01 +$currpoint sec +$hourN hour" +"%s"`
      currpointsec=`date -u -d "1970/01/01 +$currpoint sec"`
      thehour=`date -u -d "$currpointsec" +"%H"`
      theday=`date -u -d "$currpointsec" +"%d"`
      if [ "X$theday" != "X$thedayprev" ]; then
        if [ -n "$thedayprev" ]; then
          daymark=`date -u -d "$currpointsec -$thehour hour" +"%s"`
          daymark=`expr \( $daymark - $from \) / $perdotX + $startX`
        fi
        thedayprev=$theday
      fi
      themonth=`date -u -d "$currpointsec" +"%m"`
      longmonth=`date -u -d "$currpointsec" +"%b"`
      theyear=`date -u -d "$currpointsec" +"%Y"`
      themark=`date -u -d "$theyear/$themonth/$theday ${thehour}:00" +"%s"`
      themark=`expr \( $themark - $from \) / $perdotX + $startX`
      [[ $themark -gt $mY2 ]] && break
      textmark=`date -u -d "1970/01/01 +$currpoint sec"`
      textmark=`date -d "$textmark" +"%H"`
      addxmarks ${themark}.5 $textmark
      daytextmark="$longmonth $theday"
      [ -n "$daymark" ] && addxlongmark $daymark $daytextmark
    done
  fi
  unset hourN
else
# So 1-hour marks are far enough from each other, and it is the maximal
# resolution possible. It's the same as the previous loop actually, but
# I leave it here to possibly add more resolution like e.g. 10 minutes
  axisX="hours"
  while [[ $currpoint -lt $to ]]
  do
    currpoint=`date -u -d "1970/01/01 +$currpoint sec +$hourN hour" +"%s"`
    currpointsec=`date -u -d "1970/01/01 +$currpoint sec"`
    thehour=`date -u -d "$currpointsec" +"%H"`
    theday=`date -u -d "$currpointsec" +"%d"`
    if [ "X$theday" != "X$thedayprev" ]; then
      if [ -n "$thedayprev" ]; then
        daymark=`date -u -d "$currpointsec -$thehour hour" +"%s"`
        daymark=`expr \( $daymark - $from \) / $perdotX + $startX`
      fi
      thedayprev=$theday
    fi
    themonth=`date -u -d "$currpointsec" +"%m"`
    longmonth=`date -u -d "$currpointsec" +"%b"`
    theyear=`date -u -d "$currpointsec" +"%Y"`
    themark=`date -u -d "$theyear/$themonth/$theday ${thehour}:00" +"%s"`
    themark=`expr \( $themark - $from \) / $perdotX + $startX`
    [[ $themark -gt $mY2 ]] && break
    textmark=`date -u -d "1970/01/01 +$currpoint sec"`
    textmark=`date -d "$textmark" +"%H"`
    addxmarks ${themark}.5 $textmark
    daytextmark="$longmonth $theday"
    [ -n "$daymark" ] && addxlongmark $daymark $daytextmark
  done
fi

unset nexthour theday themonth theyear themark currpoint hourX

########  Here ends the X-Axis marks definition part

# Now for Y
# Finding out what per mark resolution might be
a=`solve 2 "$perdotY * $countminY / 100"`
b=`solve 2 "2 * $a"`
s=`expr length ${b%%.*}`
[ -z "$s" ] && s=1
pof=1
for ((i=0; i<$s; i++)); do pof="${pof}0"; done
log "a=$a b=$b s=$s pof=$pof"
res=`expr $pof / 10`
log "/10 :: res=$res"
if [[ $res -lt ${a%%.*} ]] ; then
  res=`expr $pof / 4`
log "/4 :: res=$res"
  if [[ $res -lt ${a%%.*} ]] ; then
    res=`expr $pof / 2`
log "/2 :: res=$res"
  fi
fi
$debug && log "Y-Axis per-mark resolution is $res"

################
### Drawing ####
################

declare -i i
declare -i imark
# where the Y axis zero is
if $minauto ; then
  imark=`expr $metricmin / $res \* $res`
log "imark=$imark"
  # how much above the axis zero the minimum value is
  shiftY=`expr $metricmin - $imark`
log "shiftY=$shiftY"
else
  imark=0
  shiftY=0
fi
ires=`expr 100 \* $res / $perdotY`
log "ires: 100 \* $res / $perdotY = $ires"
i=`expr $legendV + $padding + $axis`
log "i: $legendV + $padding + $axis = $i"
imax=`expr $i + $areaV`
log "imax: $i + $areaV = $imax"

while true
do
  i+=$ires
  imark+=$res
  
  [[ $i -gt $imax ]] && break
  # Freeing some room for axis Y title
  [[ `expr $i + $ires` -gt $imax ]] && unset imark imarkfp
  irev=`expr $graphV - $i`
  marksY="$marksY`echo "<line x1=\\"$mY1\\" y1=\\"${irev}.5\\" x2=\\"$mY2\\" y2=\\"${irev}.5\\" />"`"
  if [ "X$scale" != "Xyes" ] ; then
    if [ -n "$perpixel" ] ; then
      textY="${textY}`echo "<text x=\\"$mYT1\\" y=\\"$irev\\" >$imark</text>"`"
    else
      [ -n "$imark" ] && imarkfp=`solve 2 "$imark/$mp"`
      textY="${textY}`echo "<text x=\\"$mYT1\\" y=\\"$irev\\" >$imarkfp</text>"`"
    fi
  fi
done
log "marks generated"

cat "$rpath/wwwtemplates/graph.head.svg.tmpl" > "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
echo "<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" width=\"$graphH\" height=\"$graphV\">" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"

# Axis
echo -e "<g id=\"axis\">\n<path id=\"y\" style=\"fill:none;stroke:#000;stroke-width:$strokewidth\" d=\"M\n ${startX},$startY ${startX},$mX2\" /><path id=\"x\" style=\"fill:none;stroke:#000;stroke-width:$strokewidth\" d=\"M $startX,$startY $mY2,$startY\" /></g>" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"

# Marks
echo -e "<g id=\"marks\" shape-rendering=\"geometricPrecision\" style=\"fill:none;stroke:#999;stroke-width:1;\">\n${marksX}\n${marksY}\n</g>\n<g id=\"marks_text\" text-rendering=\"optimizeSpeed\" font-family=\"Verdana\" font-size=\"$fontsize\" fill=\"#666\">$textX" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
[ "X$scale" == "Xyes" ] || echo $textY >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
echo "<text font-family=\"Verdana\" font-size=\"$fontsize\" fill=\"#666\" x=\"$axisXX\" y=\"$axisXY\">$axisX</text>" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
[ "X$scale" == "Xyes" ] || echo "<text x=\"$axisYX\" y=\"$axisYY\" font-family=\"Verdana\" font-size=\"$fontsize\" fill=\"#666\">$axisY</text>" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
echo "</g>" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"

# Graphs
i=0
if [ "$legendpos" == "left" ]; then
  slegendX=`solve 2 "$startX - $legend"`
  slegendY=$startY
  sadd=`expr \( $graphV - $padding \) / $sn`
else
  slegendX=$padding
  slegendY=$axisXY
  sadd=`expr 2 \* $fontsize`
fi
log "slegendX=$slegendX  slegendY=$slegendY  sadd=$sadd"

echo "<g id=\"graph\" shape-rendering=\"geometricPrecision\">" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"

# first column is the X axis, data starts from the column 2
declare -i n
[ -z "$perpixel" ] && n=2 || n=1
for smetric in `echo $metric | tr ',' ' '` ; do

  slegend="${slegend}`echo "<text font-family=\\"Verdana\\" font-size=\\"${fontsize}\\" fill=\\"${colors[$i]}\\" x=\\"$slegendX\\" y=\\"$slegendY\\" >$smetric</text>"`"
log "slegend=$slegend"
  
  if [ "$legendpos" == "left" ]; then
    slegendY=`expr $slegendY - $sadd`
  else
    slegendY=`expr $slegendY + $sadd`
  fi
log "slegendY=$slegendY"

  echo -n "<path id=\"graph_${smetric}\" style=\"fill:none;stroke:${colors[$i]};stroke-width:${strokewidth}\" d=\"M" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
  if [ -z "$perpixel" ]; then  
    if [ "X$scale" == "Xyes" ] ; then cat "$M_TEMP/graph.${sIP}.${dbname}.${smetric}.scaled" ; else cat "$M_TEMP/graph.${sIP}.${dbname}.${name}" | cut -d'|' -f1,${n} ; fi | while read LINE
    do
      X=`echo $LINE | cut -d'|' -f1`
      Y=`echo $LINE | cut -d'|' -f2` ; Y=${Y%.*}
      if [ "X$X" == "X" ] || [ "X$Y" == "X" ] ; then continue ; fi
      X=`expr \( $X - $from \) / $perdotX + $padding + $legendH + $axis`
      Y=`expr $areaV + $padding - \( $Y - $metricmin + $shiftY \) \* 100 / $perdotY`
      printf " $X,$Y" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
    done
#### drawing perpixel graph
  else
    declare -i X
    X=`expr $padding + $legendH + $axis`
    shiftYY=`expr $areaV + $padding + $metricmin - $shiftY`
    tac "$M_TEMP/graph.${sIP}.${dbname}.${name}" | cut -d'|' -f${n} | while read LINE
    do
      Y=${LINE%.*}
      [ -z "$Y" ] && Y=$Yp || Yp=$Y
      [ -z "$Y" ] && Y=0
      X+=1
      Y=`expr $shiftYY - $Y`
      printf " $X,$Y" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
    done
  fi
  echo "\" />" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
  i+=1
  n+=1
done

echo "</g>" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
echo "<g id=\"legend\" text-rendering=\"optimizeSpeed\">" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
echo "$slegend" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
echo "</g>" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"
echo "</svg>" >> "$rpath/www/graphs/${sIP}.${dbname}.${name}.svg"

#convert -size ${graphH}x${graphV} xc:white -family $fontfamily -pointsize $fontsize \
#  -strokewidth $strokewidth \
#  -draw "stroke black line $startX,$startY $mY2,$startY" \
#  -draw "stroke black line $startX,$startY $startX,$mX2" \
#  -strokewidth 1 \
#  -draw "stroke gray $marksX " -draw "stroke gray $marksY " \
#  -draw "$textY " -draw "$textX " \
#  -draw "${datalines}" \
#  -draw "text $axisXX,$axisXY `printf "\'$axisX\'"`" \
#  -draw "text $axisYX,$axisYY `printf "\'$metric\'"`" \
#  -pointsize $pointsize \
#  -draw "text $titleX,$titleY `printf "\'$title\'"`" \
#  "${rpath}/www/graphs/${sIP}.${dbname}${name}.png"






