#!/bin/bash
ba=`which bash 2>/dev/null`
[ $? -ne 0 ] && echo -e "\nBash is required" && exit 1
[ $USER != "root" ] && echo -e "\nYou must be root" && exit 1
rpath=$(readlink -f "$BASH_SOURCE")
rpath=${rpath%/*}
M_ROOT="$rpath"
export M_ROOT
#*/
if [ -n "$1" ]; then
  $ba --rcfile "$rpath"/m.rc "$1"
else
  $ba --rcfile "$rpath"/m.rc
fi

