#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")

possible_options="cloud"
necessary_options=""

IFS1=$IFS
IFS='-'
for s_option in "$@"
do
  s_option=${s_option/--/}
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "o$s_optarg" == "o$s_optname" ] && unset s_optarg

  for option in ${possible_options// /-} ; do
    [ "o$s_optname" == "o$option" ] && eval "$s_optname=\"$s_optarg\"" && break
  done

done
IFS=$IFS1

if [ -n "$cloud" ]; then
  cld=$cloud
else
  cld=$CLOUD
fi

[ -z "$cld" ] && echo "cloud is not defined" && exit 1

if [ -e "$M_ROOT/conf/clouds/${cld}.conf" ]; then
  source "$M_ROOT/conf/clouds/${cld}.conf"
else
  echo "Cloud $cld configuration not found (conf/clouds/${cld}.conf)"
  exit 1
fi

export CLOUD=$cld
if [ -z "$CLOUD_PROVIDER" ]; then
  "$M_ROOT"/cloud/common/find_noncloud_server --cloud=$cld $@
else
  "$M_ROOT"/cloud/$CLOUD_PROVIDER/find_server --cloud=$cld $@
fi

