#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")

possible_options="cloud"
necessary_options=""

IFS1=$IFS
IFS='-'
for s_option in "$@"
do
  s_option=${s_option/--/}
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "_$s_optarg" == "_$s_optname" ] && unset s_optarg

  for option in ${possible_options// /-} ; do
    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && break
  done

done
IFS=$IFS1

if [ -n "$cloud" ]; then
  cld=$cloud
else
  cld=$CLOUD
fi

[ -z "$cld" ] && echo "cloud is not defined" && exit 1
export CLOUD=$cld
source "$M_ROOT/conf/clouds/${cld}.conf"
if [ -x "$M_ROOT/cloud/$CLOUD_PROVIDER/save_node" ]; then
  "$M_ROOT"/cloud/$CLOUD_PROVIDER/save_node --cloud=$cld $@
else
  exit 2
fi

exit 0



