#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")

possible_options="cloud"
necessary_options=""

IFSORIG=$IFS
IFS='-'
for s_option in "$@"
do
  s_option=${s_option/--/}
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "o$s_optarg" == "o$s_optname" ] && unset s_optarg

  for option in ${possible_options// /-} ; do
    [ "o$s_optname" == "o$option" ] && eval "$s_optname=\"$s_optarg\"" && break
  done

done
IFS=$IFSORIG

if [ -n "$cloud" ]; then
  cloud=`echo -e "$cloud" | tr ',' '\n'`
elif [ -n "$CLOUD" ]; then
  cloud=$CLOUD
else
  cloud=`cat "$M_ROOT/conf/clusters.conf" | grep -vE "^$|^#|^[[:space:]]*#" | cut -d'|' -f12 | sort | uniq | grep -v ^$`
fi

for cld in $cloud ; do
  [ -n "$PS1" ] && echo "*** Cloud $cld"
  export CLOUD=$cld
  source "$M_ROOT/conf/clouds/${cld}.conf"
  if [ -n "$CLOUD_PROVIDER" ]; then
    "$M_ROOT"/cloud/$CLOUD_PROVIDER/show_servers --cloud=$cld $@
  else
    "$M_ROOT"/cloud/common/show_noncloud_servers --cloud=$cld $@
  fi
done

