#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")

possible_options="cloud"
necessary_options=""

IFS1=$IFS
IFS='-'
for s_option in "$@"
do
  s_option=${s_option/--/}
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "X$s_optarg" == "X$s_optname" ] && unset s_optarg

  for option in ${possible_options// /-} ; do
    [ "X$s_optname" == "X$option" ] && eval "$s_optname=\"$s_optarg\"" && break
  done

done
IFS=$IFS1

if [ -n "$cloud" ]; then
  cloud=`echo -e "$cloud" | tr ',' '\n'`
elif [ -n "$CLOUD" ]; then
  cloud=$CLOUD
else
  cloud=`cat "$M_ROOT/conf/clusters.conf" | grep -vE "^$|^#|^[[:space:]]*#" | cut -d'|' -f12 | sort | uniq | grep -v ^$`
fi

for cld in $cloud ; do
  source "$M_ROOT/conf/clouds/${cld}.conf"
  "$M_ROOT"/cloud/$CLOUD_PROVIDER/show_servers --cloud=$cld $@
done

