#!/bin/bash
# Copyright (C) 2008-2014 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$M_ROOT/conf/mon.conf"

IFS1=$IFS
IFS='
'
# in case the file doesn't end correctly
[ `cat -E /etc/hosts | tail -1 | grep -c \$$` -eq 0 ] && echo >> /etc/hosts
while [ `cat /etc/hosts | tail -1 | grep -c ^$` -eq 1 ] ; do sed -i '$d' /etc/hosts ; done
cat "$M_ROOT/servers.list" | grep -vE "^[[:space:]]*$|^[[:space:]]*#|^#|^$" | cut -d'|' -f1,4 | while read HOST
do
  ip=`echo $HOST | cut -d'|' -f1`
  hname=`echo $HOST | cut -d'|' -f2`
  [ -z "$hname" ] && error+=("Server $ip has no name") && continue
  if [ `grep -c "$ip " /etc/hosts` -ge 1 ] ; then
    sed -i "/$ip /d" /etc/hosts
  fi
  if [ `grep -c " $hname " /etc/hosts` -ge 1 ] ; then
    sed -i "/ $hname /d" /etc/hosts
  fi
  if [ `grep -c " $hname$" /etc/hosts` -ge 1 ] ; then
    sed -i "/ $hname$/d" /etc/hosts
  fi
  echo "$ip $hname" >> /etc/hosts
done


[ -n "$error" ] && echo "${error[*]}" && exit 1
if [ -n "$1" ]; then
  if [ "$1" == "everywhere" ]; then
    echo "Syncing servers.list to all clusters"
    for cluster in `cat "$M_ROOT/conf/clusters.conf" | grep -vE "^[[:space:]]*$|^[[:space:]]*#|^#|^$" | grep -v ^$SUPER_CLUSTER\|` ; do
      clustername=`echo "$cluster" | cut -sd'|' -f1`
      mpath=`echo "$cluster" | cut -sd'|' -f8`
      sudouser=`echo "$cluster" | cut -sd'|' -f13`
      [ -z "$mpath" ] && mpath=$M_ROOT
      if [ -n "$sudouser" ]; then
        "$rpath"/cloudexec --nolocalhost --cluster=$clustername mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
        "$rpath"/cloudsync --nolocalhost --cluster=$clustername "$M_ROOT/servers.list" /tmp
        "$rpath"/cloudexec --nolocalhost --cluster=$clustername mv /tmp/servers.list "\"$mpath\"/servers.list"
        "$rpath"/cloudexec --nolocalhost --cluster=$clustername "\"$mpath\"/cloud/common/$rcommand"
        "$rpath"/cloudexec --nolocalhost --cluster=$clustername mv "\"$M_ROOT\"/servers.list.tmp" "$M_ROOT/servers.list"
      else
        "$rpath"/cloudexec --nolocalhost --cluster=$clustername mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
        "$rpath"/cloudsync --nolocalhost --cluster=$clustername "$M_ROOT/servers.list" "\"$mpath\"/servers.list"
        "$rpath"/cloudexec --nolocalhost --cluster=$clustername "\"$mpath\"/cloud/common/$rcommand"
        "$rpath"/cloudexec --nolocalhost --cluster=$clustername mv "\"$M_ROOT\"/servers.list.tmp" "\"$M_ROOT\"/servers.list"
      fi
    done
  else
    mpath=`grep ^$1\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f8`
    [ -z "$mpath" ] && mpath=$M_ROOT
    if [ -n "$sudouser" ]; then
      "$rpath"/cloudsync --nolocalhost --cluster="$1" "$M_ROOT/servers.list" /tmp
      "$rpath"/cloudexec --nolocalhost --cluster="$1" mv /tmp/servers.list "\"$mpath\"/"
      "$rpath"/cloudexec --nolocalhost --cluster="$1" "\"$mpath\"/cloud/common/$rcommand"
    else
      "$rpath"/cloudsync --nolocalhost --cluster="$1" "$M_ROOT/servers.list" "\"$mpath\"/"
      "$rpath"/cloudexec --nolocalhost --cluster="$1" "\"$mpath\"/cloud/common/$rcommand"
    fi
  fi
else
  if [ `cat "$M_ROOT/conf/clusters.conf" | cut -sd'|' -f1 | grep -v "^$" | grep -c "^${1}$"` -eq 1 ]; then
    echo "Syncing servers.list to cluster $1"
    mpath=`cat "$M_ROOT/conf/clusters.conf" | grep "^${1}|" | cut -sd'|' -f8`
    sudouser=`cat "$M_ROOT/conf/clusters.conf" | grep "^${1}|" | cut -sd'|' -f13`
    [ -z "$mpath" ] && mpath=$M_ROOT
    if [ -n "$sudouser" ]; then
      "$rpath"/cloudexec --nolocalhost --cluster=$1 mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
      "$rpath"/cloudsync --nolocalhost --cluster=$1 "$M_ROOT/servers.list" /tmp
      "$rpath"/cloudexec --nolocalhost --cluster=$1 mv /tmp/servers.list "\"$mpath\"/servers.list"
      "$rpath"/cloudexec --nolocalhost --cluster=$1 "\"$mpath\"/cloud/common/$rcommand"
      "$rpath"/cloudexec --nolocalhost --cluster=$1 mv "\"$M_ROOT\"/servers.list.tmp" "$M_ROOT/servers.list"
    else
      "$rpath"/cloudexec --nolocalhost --cluster=$1 mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
      "$rpath"/cloudsync --nolocalhost --cluster=$1 "$M_ROOT/servers.list" "\"$mpath\"/servers.list"
      "$rpath"/cloudexec --nolocalhost --cluster=$1 "\"$mpath\"/cloud/common/$rcommand"
      "$rpath"/cloudexec --nolocalhost --cluster=$1 mv "\"$M_ROOT\"/servers.list.tmp" "\"$M_ROOT\"/servers.list"
    fi
  elif [ `cat "$M_ROOT/servers.list" | cut -sd'|' -f1 | grep -v "^$" | grep -c "^${1}$"` -eq 1 ]; then
    echo "Syncing servers.list to server $1"
    cluster=`cat "$M_ROOT/servers.list" | grep "^${1}|" | cut -sd'|' -f5`
    mpath=`cat "$M_ROOT/conf/clusters.conf" | grep "^${cluster}|" | cut -sd'|' -f8`
    sudouser=`cat "$M_ROOT/conf/clusters.conf" | grep "^${cluster}|" | cut -sd'|' -f13`
    [ -z "$mpath" ] && mpath=$M_ROOT
    if [ -n "$sudouser" ]; then
      "$rpath"/cloudexec --nolocalhost --ip=$1 mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
      "$rpath"/cloudsync --nolocalhost --ip=$1 "$M_ROOT/servers.list" /tmp
      "$rpath"/cloudexec --nolocalhost --ip=$1 mv /tmp/servers.list "\"$mpath\"/servers.list"
      "$rpath"/cloudexec --nolocalhost --ip=$1 "\"$mpath\"/cloud/common/$rcommand"
      "$rpath"/cloudexec --nolocalhost --ip=$1 mv "\"$M_ROOT\"/servers.list.tmp" "$M_ROOT/servers.list"
    else
      "$rpath"/cloudexec --nolocalhost --ip=$1 mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
      "$rpath"/cloudsync --nolocalhost --ip=$1 "$M_ROOT/servers.list" "\"$mpath\"/servers.list"
      "$rpath"/cloudexec --nolocalhost --ip=$1 "\"$mpath\"/cloud/common/$rcommand"
      "$rpath"/cloudexec --nolocalhost --ip=$1 mv "\"$M_ROOT\"/servers.list.tmp" "\"$M_ROOT\"/servers.list"
    fi
  elif [ `cat "$M_ROOT/servers.list" | cut -sd'|' -f4 | grep -v "^$" | grep -c "^${1}$"` -eq 1 ]; then
    echo "Syncing servers.list to server $1"
    cluster=`cat "$M_ROOT/servers.list" | cut -sd'|' -f4,5 | grep "^${1}|" | cut -sd'|' -f2`
    mpath=`cat "$M_ROOT/conf/clusters.conf" | grep "^${cluster}|" | cut -sd'|' -f8`
    sudouser=`cat "$M_ROOT/conf/clusters.conf" | grep "^${cluster}|" | cut -sd'|' -f13`
    ip=`cat "$M_ROOT/servers.list" | cut -sd'|' -f1,4 | grep "|${1}$" | cut -sd'|' -f1`
    [ -z "$mpath" ] && mpath=$M_ROOT
    if [ -n "$sudouser" ]; then
      "$rpath"/cloudexec --nolocalhost --ip=$ip mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
      "$rpath"/cloudsync --nolocalhost --ip=$ip "$M_ROOT/servers.list" /tmp
      "$rpath"/cloudexec --nolocalhost --ip=$ip mv /tmp/servers.list "\"$mpath\"/servers.list"
      "$rpath"/cloudexec --nolocalhost --ip=$ip "\"$mpath\"/cloud/common/$rcommand"
      "$rpath"/cloudexec --nolocalhost --ip=$ip mv "\"$M_ROOT\"/servers.list.tmp" "$M_ROOT/servers.list"
    else
      "$rpath"/cloudexec --nolocalhost --ip=$ip mv "\"$M_ROOT\"/servers.list" "\"$M_ROOT\"/servers.list.tmp"
      "$rpath"/cloudsync --nolocalhost --ip=$ip "$M_ROOT/servers.list" "\"$mpath\"/servers.list"
      "$rpath"/cloudexec --nolocalhost --ip=$ip "\"$mpath\"/cloud/common/$rcommand"
      "$rpath"/cloudexec --nolocalhost --ip=$ip mv "\"$M_ROOT\"/servers.list.tmp" "\"$M_ROOT\"/servers.list"
    fi
  fi
fi

IFS=$IFS1
