#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$M_ROOT/lib/cloud_functions.sh"

declare -a catline

for cld in `cat "$M_ROOT/conf/clusters.conf" | grep -vE "^#|^[[:space:]]#|^$" | cut -d'|' -f12 | sort | uniq | grep -v ^$`; do
  source "$M_ROOT/conf/clouds/${cld}.conf"
  [ -n "$CLOUD_PROVIDER" ] && "$M_ROOT"/cloud/$CLOUD_PROVIDER/show_servers --cloud=$cld --forceupdate --update_servers_list $@
  res=$?
  [ $res -eq 10 ] && log "$cld list is not updated: failed to acquire cloud operations lock" && continue
  [ $res -eq 0 ] && log "$cld list updated successfully"
  [ $res -eq 1 ] && log "ERROR $cld list is not updated" && continue
  catline+=("$M_ROOT/cloud/servers.list.${cld}")
done

log "concatenating cloud lists: ${catline[*]}"
[ -n "${catline[*]}" ] && cat "${catline[*]}" > "$M_ROOT/servers.list" 2>/dev/null

