#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")

for cld in `cat "$M_ROOT/conf/clusters.conf" | grep -vE "^#|^[[:space:]]#|^$" | cut -d'|' -f12 | sort | uniq | grep -v ^$`; do
  source "$M_ROOT/conf/clouds/${cld}.conf"
  "$M_ROOT"/cloud/$CLOUD_PROVIDER/show_servers --cloud=$cld --forceupdate --update_servers_list $@
  catline="$catline \"$M_ROOT/cloud/servers.list.${cld}\""
done

cat $catline > "$M_ROOT/servers.list"

