#!/bin/bash
# Copyright (C) 2008-2014 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/lib/cloud_functions.sh"

IFS1=$IFS
IFS='
'
# in case the file doesn't end correctly
[ `cat -E /etc/hosts | tail -1 | grep -c \$$` -eq 0 ] && echo >> /etc/hosts
while [ `cat /etc/hosts | tail -1 | grep -c ^$` -eq 1 ] ; do sed -i '$d' /etc/hosts ; done
if [ -n "$2" ]; then
  for clfilter in `echo "$2" | tr ',' '\n'`; do
    hosts="$hosts\n`cat "$M_ROOT/nodes.list" | grep -vE "^[[:space:]]*$|^[[:space:]]*#|^#|^$" | cut -d'|' -f1,4,5 | grep -E "\|${clfilter}$" | cut -d'|' -f1,2`"
  done
else
  hosts=`cat "$M_ROOT/nodes.list" | grep -vE "^[[:space:]]*$|^[[:space:]]*#|^#|^$" | cut -d'|' -f1,4`
fi
for HOST in `echo -e "$hosts" | grep -v ^$` ; do
  ip=`echo $HOST | cut -d'|' -f1`
  hname=`echo $HOST | cut -d'|' -f2`
  [ -z "$hname" ] && error+=("Server $ip has no name") && continue
  sed -i "/^$ip \| $ip /d" /etc/hosts
  sed -i "/ $hname \| $hname$/d" /etc/hosts
  if [ -n "$DOMAIN" ]; then
    echo "$ip ${hname}.${DOMAIN} $hname" >> /etc/hosts
  else
    echo "$ip $hname" >> /etc/hosts
  fi
  if [ -n "$1" ]; then
    if [ "$1" == "everywhere" ]; then
      cloudexec --cluster=all --nolocalhost \(sed -i \\\"/^$ip \\\| $ip /d\\\" /etc/hosts \; sed -i \\\"/ $hname \\\| $hname$/d\\\" /etc/hosts \; echo \\\"$ip $hname\\\" \>\> /etc/hosts\)
    else
      args=`echo "$@" | tr ',' ' '`
      for arg in $args ; do
        if [ `cat "$M_ROOT/conf/clusters.conf" | cut -sd'|' -f1 | grep -vE "^[[:space:]]*$|^[[:space:]]*#|^#|^$" | grep -v "^$" | grep -c "^${arg}$"` -eq 1 ]; then
          cloudexec --cluster="$arg" --nolocalhost \(sed -i \\\"/^$ip \\\| $ip /d\\\" /etc/hosts \; sed -i \\\"/ $hname \\\| $hname$/d\\\" /etc/hosts \; echo \\\"$ip $hname\\\" \>\> /etc/hosts\)
        else
          IP=`name_to_ip $arg || echo $arg`
          cloudexec --ip=$IP --nolocalhost \(sed -i \\\"/^$ip \\\| $ip /d\\\" /etc/hosts \; sed -i \\\"/ $hname \\\| $hname$/d\\\" /etc/hosts \; echo \\\"$ip $hname\\\" \>\> /etc/hosts\)
        fi
      done
    fi
  fi
done

[ -n "$error" ] && echo "${error[*]}" && exit 1

IFS=$IFS1
