#!/usr/bin/env bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$M_ROOT/conf/mon.conf"

IFS1=$IFS
IFS='
'
# in case the file doesn't end correctly
[ `cat -E /etc/hosts | tail -1 | grep -c \$$` -eq 0 ] && echo >> /etc/hosts
while [ `cat /etc/hosts | tail -1 | grep -c ^$` -eq 1 ] ; do sed -i '$d' /etc/hosts ; done
cat "$M_ROOT/servers.list" | grep -v ^[[:space:]]*$ | grep -v ^[[:space:]]*# | cut -d'|' -f1,4 | while read HOST
do
  ip=`echo $HOST | cut -d'|' -f1`
  hname=`echo $HOST | cut -d'|' -f2`
  [ -z "$hname" ] && error+=("Server $ip has no name") && continue
  if [ `grep -c "$ip[[:space:]]*$hname$" /etc/hosts` -eq 0 ] ; then
    if [ `grep -c "$ip " /etc/hosts` -eq 1 ] ; then
      sed -i -e "/$ip /d" /etc/hosts
    fi
    if [ `grep -c " $hname " /etc/hosts` -eq 1 ] ; then
      sed -i -e "/ $hname /d" /etc/hosts
    fi
    if [ `grep -c " $hname$" /etc/hosts` -eq 1 ] ; then
      sed -i -e "/ $hname$/d" /etc/hosts
    fi
    echo "$ip $hname" >> /etc/hosts
  fi
done
IFS=$IFS1

[ -n "$error" ] && echo "${error[*]}" && exit 1
if [ -n "$1" ] ; then
  if [ "$1" == "everywhere" ] ; then
    echo "Syncing servers.list to all clusters"
    for cluster in `cat "$M_ROOT/conf/clusters.conf" | grep -v ^[[:space:]]*$ | grep -v ^[[:space:]]*# | grep -v ^$SUPER_CLUSTER\|` ; do
      clustername=`echo $cluster | cut -d'|' -f1`
      mpath=`echo $cluster | cut -d'|' -f8`
      if [ -n "$mpath" ] ; then
        "${rpath}"/cloudsync --cluster=$clustername "$M_ROOT/servers.list" "${mpath}/"
        "${rpath}"/cloudexec --cluster=$clustername "${mpath}/cloud/common/${rcommand}"
      fi
    done
  else
    mpath=`grep ^$1\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f8`
    if [ -n "$mpath" ] ; then
      "${rpath}"/cloudsync --nolocalhost --cluster=$1 "$M_ROOT/servers.list" "${mpath}/"
      "${rpath}"/cloudexec --nolocalhost --cluster=$1 "${mpath}/cloud/common/${rcommand}"
    fi
  fi
fi

