#!/bin/bash

M_ROOT="$PWD/../.."
source "$M_ROOT/conf/dash.conf"
source "$M_ROOT/lib/dash_functions.sh"

publish_graph `"$M_ROOT"/graph --database=standalone/MySQL/mysqlstatus.db --table=mysqlstatus --metric=aborted_clients --where="dbhost:${2##*/}" --perpixel --width=750 --height=300 --padding=10 --legend=160 2>&1`
