#!/bin/bash
rpath=$(readlink -f "$BASH_SOURCE")
rcommand=${rpath##*/}
rpath=${rpath%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$rpath/../../lib/functions.sh"
KEEP_LOG=false
source "$rpath/postfix.conf"

if [ -e "$rpath/data/error.log" ]; then
  for sn in `cat "$rpath/error_patterns.conf" | grep -vE "^$|^#|^[[:space:]]#" | cut -sd'|' -f1,2 | sort | uniq` ; do
    status=${sn%%|*}
    errnum=${sn##*|}
    pattern=`grep "^$sn|" "$rpath/error_patterns.conf" | grep -v '|%.*%$' | cut -d'|' -f3 | tr '\n' '|'`
    pattern=${pattern%|}
    exclpattern=`grep "^$sn|" "$rpath/error_patterns.conf" | grep '|%.*%$' | cut -d'|' -f3 | tr '\n' '|' | tr -d '%'`
    exclpattern=${exclpattern%|}
    if [ -n "$pattern" ]; then
      if [ -n "$exclpattern" ]; then
        if [ -n "$errnum" ]; then
          match=`grep "|$status|" "$rpath/data/error.log" | cut -d'|' -f1,3 | grep -v '^$' | grep " $errnum " | grep -viE "$exclpattern" | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
        else
          match=`grep "|$status|" "$rpath/data/error.log" | cut -d'|' -f1,3 | grep -v '^$' | grep -viE "$exclpattern" | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
        fi
      else
        if [ -n "$errnum" ]; then
          match=`grep "|$status|" "$rpath/data/error.log" | cut -d'|' -f1,3 | grep -v '^$' | grep " $errnum " | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
        else
          match=`grep "|$status|" "$rpath/data/error.log" | cut -d'|' -f1,3 | grep -v '^$' | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
        fi
      fi
    fi
    matched=`echo -n "$match" | wc -l`
    if [ $matched -gt 0 ]; then
      echo "$match" >> "$rpath/data/${status}.${errnum}.log"
      echo "<**> Pattern match for status ${status}, error number ${errnum}:  $matched times"
    else
      echo "<OK> No pattern match for status ${status}, error number ${errnum}"
    fi
  done
  $KEEP_LOG && cat "$rpath/data/error.log" 2>/dev/null >> "$rpath/data/error.log.save" || rm "$rpath/data/error.log"
else
  echo "<OK> Error log is empty"
fi

