#!/bin/bash
rpath=$(readlink -f "$BASH_SOURCE")
rcommand=${rpath##*/}
rpath=${rpath%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$rpath/../../lib/functions.sh"
KEEP_LOG=false
RECIPIENT_STATS=false

source "$rpath/postfix.conf"

[ -z "$1" ] && errorlog="$rpath/data/error.log" || errorlog="$1"

IFS='
'

if [ -e "$errorlog" ]; then
  conf=`cat "$rpath/error_patterns.conf" | grep -vE "^$|^#|^[[:space:]]#"`
  for rule in `echo "$conf" | cut -sd'|' -f1 | sort | uniq` ; do
    [ -z "$rule" ] && continue
    match_cond=`echo "$conf" | grep "^$rule|" | cut -sd'|' -f2,3,4 | sort | uniq | grep -v ^$`
    for status_errnum in `echo "$match_cond" | cut -sd'|' -f1,2 | sort | uniq` ; do
    
      errnum=`echo "$status_errnum" | cut -sd'|' -f2`
      status=`echo "$status_errnum" | cut -sd'|' -f1`
      pattern=`echo "$match_cond" | grep "^$status_errnum|" | grep -v '|%.*%$' | cut -d'|' -f3 | tr '\n' '|'`
      pattern=${pattern%|}
      exclpattern=`echo "$match_cond" | grep "^$status_errnum|" | grep '|%.*%$' | cut -d'|' -f3 | tr '\n' '|' | tr -d '%'`
      exclpattern=${exclpattern%|}
      
      if [ -n "$pattern" ]; then
        if [ -n "$exclpattern" ]; then
          if [ -n "$errnum" ]; then
            match=`grep "|$status|" "$errorlog" | cut -d'|' -f1,3 | grep -v '^$' | grep " $errnum " | grep -viE "$exclpattern" | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
          else
            match=`grep "|$status|" "$errorlog" | cut -d'|' -f1,3 | grep -v '^$' | grep -viE "$exclpattern" | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
          fi
        else
          if [ -n "$errnum" ]; then
            match=`grep "|$status|" "$errorlog" | cut -d'|' -f1,3 | grep -v '^$' | grep " $errnum " | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
          else
            match=`grep "|$status|" "$errorlog" | cut -d'|' -f1,3 | grep -v '^$' | grep -iE "$pattern" | cut -d'|' -f1,2 | sort | uniq`
          fi
        fi
      else
        if [ -n "$errnum" ]; then
          match=`grep "|$status|" "$errorlog" | cut -d'|' -f1,3 | grep -v '^$' | grep " $errnum " | cut -d'|' -f1,2 | sort | uniq`
        else
          match=`grep "|$status|" "$errorlog" | cut -d'|' -f1,3 | grep -v '^$' | cut -d'|' -f1,2 | sort | uniq`
        fi
      fi
      matched=`echo -n "$match" | wc -l`
      if [ $matched -gt 0 ]; then
        echo "$match" >> "$rpath/data/${rule}.log"
        echo "<**> Pattern match for rule '$rule', error number '$errnum', status '$status':  $matched times"
        if $RECIPIENT_STATS ; then
          for line in `echo "$match"`; do
            to=`echo "$line" | cut -sd'|' -f1`
            sdate=`echo "$line" | cut -sd'|' -f4`
            sdate=`date -d "$sdate" +"%s" 2>/dev/null`
            sreason=`echo "$line" | cut -sd'|' -f3`
            [ -z "$sdate" ] && sdate=`date +"%s"`
            dbquery "$rpath/data/recipients.db" "UPDATE recipients SET custom_date='$sdate', custom='$rule', custom_reason='$sreason' WHERE email='$to'"
          done
        fi
      else
        echo "<OK> No pattern match for rule '$rule', error number '$errnum', status '$status'"
      fi
      
    done
  done
  $KEEP_LOG && cat "$rpath/data/error.log" 2>/dev/null >> "$rpath/data/error.log.save"
  rm "$rpath/data/error.log"
else
  echo "<OK> Error log is empty"
fi

IFS=$IFSORIG


