#!/bin/bash
# Copyright (C) 2008-2016 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")

CURL=`which curl 2>/dev/null`
[ -z "$CURL" ] && echo "Curl not found" && exit 1
SSLEX=`which openssl 2>/dev/null`
[ -z "$SSLEX" ] && echo "openssl binary not found" && exit 1

CURL="$CURL -s -k"

possible_options="cloud cluster id name ip return verbose log_request"
necessary_options=""
ARGV=`echo $@ | sed 's/^--//;s/ --/|/g;s/ /|/g'`
[ -z "$ARGV" ] && echo "Node details? Which node?" && exit 1
IFS1=$IFS
IFS='|'
for s_option in $ARGV
do
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "_$s_optarg" == "_$s_optname" ] && s_optarg="yes"
  found=false
  for option in `echo $possible_options | sed 's/ /|/g'`; do 
    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true
  done
  if ! $found ; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done

found=0
for option in `echo $necessary_options | sed 's/,//g'`; do
  [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options}, --${option}" && found=1
done
if [[ $found -eq 1 ]]; then
  missing_options=${missing_options#*,}
  echo "Necessary options: $missing_options not found"
  exit 1
fi

IFS=$IFS1

[ -n "$cloud" ] && CLOUD=$cloud
[ -z "$CLOUD" ] && echo "CLOUD not defined" && exit 1
export CLOUD

[ -n "$debug" ] && debug=true || debug=false

source "$M_ROOT/conf/mon.conf"
M_TEMP="$M_TEMP/cloud/$CLOUD"
[ -d "$M_TEMP" ] || install -d "$M_TEMP"
source "$M_ROOT/conf/clouds/${CLOUD}.conf"
source "$M_ROOT/lib/cloud_functions.sh"
source "$rpath/functions.sh"

exit_status=0

if [ -z "$region" ]; then
  [ -n "$cluster" ] && region=`find_region $cluster` || region=`find_region`
  [ `echo "$region" | wc -l` -gt 1 ] && echo "More than one region returned for cluster $region_cluster" && exit 1
  [ -z "$region" ] && region=$DEFAULT_REGION
  [ -z "$region" ] && region="us-east-1"
  log "searching nodes in region $region"
fi

METHOD=GET
ACTION=DescribeInstances
SERVICE=ec2
ENDPOINT="ec2.${region}.amazonaws.com"
VERSION="2013-10-15"
AUTHMETHOD=header

find_by_id() {
  qparams="Filter.1.Name=instance-id&Filter.1.Value.1=${1}"
}

find_by_ip() {
  if [ "_$NETWORK" == "_external" ]; then
    qparams="Filter.1.Name=ip-address&Filter.1.Value.1=${1}"
  else
    qparams="Filter.1.Name=private-ip-address&Filter.1.Value.1=${1}"
  fi
}

printreturn() {
  reservationId=`echo "$1" | grep '"reservationId"/' | cut -sd'|' -f2 | tr -d '"'`
  [ -z "$reservationId" ] && return 1
  case $return in
  grep|greppable)
    for sn in `echo "$1" | cut -d'/' -f5,6,7,8,9,10,11,12 | sort | uniq`; do
      echo "*** $sn ***"
      echo "$1" | cut -d'/' -f13- | tr -d '"'
    done
    ;;
  yaml)
    echo "$1" | "$M_ROOT"/lib/txt2yaml
    ;;
  *)
    echo "Unknown output format: $return"
    ;;
  esac
}

lock_cloudops || exit 10

if [ -z "$id" ] ; then
  if [ -z "$ip" ] ; then
    if [ -z "$name" ] ; then
      echo "One of id, ip or name is required to identify the node"
      proper_exit 1 145
    else
      ip=`cat "$rpath/../../nodes.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
      if [ -n "$ip" ] ; then
        find_by_ip $ip
      fi
    fi
  else
    find_by_ip $ip
  fi
else
  find_by_id $id
fi

[ -n "$verbose" ] && log "sending request"
reqparsed=`aws_api_request $SERVICE $VERSION $AUTHMETHOD $METHOD $ENDPOINT $ACTION $qparams`
echo "$reqparsed" > "$M_TEMP/${rcommand}.resp"
[ `echo "$reqparsed" | wc -l` -eq 0 ] && log "parsed response to $rcommand is empty" && proper_exit 1 153
[ `echo "$reqparsed" | grep -c Error` -ne 0 ] && log "request failed with error `echo "$reqparsed" | grep Error | cut -d'|' -f2`" && proper_exit 1 154

printreturn "$reqparsed" || exit_status=2

proper_exit $exit_status 158
