#!/bin/bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


rcommand=${0##*/}
rpath=${0%/*}
#*/

store_vars() {
  if [ -f "${tmpfile}.var" ]; then
    [ -n "$verbose" ] && echo "Reading existing variables"
    source "${tmpfile}.var"
  fi
  [ -n "$verbose" ] && echo "Sourcing $1"
  for LINE in `cat "$1" | grep -vE "^[[:space:]]*$|^[[:space:]]*#"` ; do
    # to respect environment variables and variables passed from command line
    pvar=`expr "$LINE" : '[[:space:]]*\([a-zA-Z0-9_]*\)=.*$'`
    if [ -n "$pvar" ]; then
      pval="`eval echo "\\$$pvar"`"
      if [ -n "$pval" ]; then
        [ `expr "$pval" : "[0-9]*$"` -eq 0 ] && echo "${pvar}=\"`eval echo "\\$$pvar"`\"" >> "${tmpfile}.var" && continue || echo "${pvar}=`eval echo "\\$$pvar"`" >> "${tmpfile}.var" && continue
      fi
    fi
    $debug && echo "  == $LINE"
    ELINE=`echo "$LINE" | sed 's|"|\\\"|g' | sed "s|'|\\\'|g" | sed 's_|_\\\|_g'`
    $debug && echo "  << $ELINE"
    # This conditional evaluation below is a workaround for hard nuts like pipes
    # inside sub-shells. More complex constructs involving both sub-shell and 
    # non-sub-shell expression in a single line both with pipes will probably 
    # not work. Just avoid such things.
    eval "$LINE" 2>/dev/null
    eval $(eval "echo \"$LINE\"") 2>/dev/null
    if [ $? -eq 0 ]; then
      $debug && echo "evaluating plain line"
      eval "echo \"$LINE\"" >> "${tmpfile}.var"
    else
      eval "$ELINE" 2>/dev/null
      eval $(eval "echo \"$ELINE\"") 2>/dev/null
      if [ $? -eq 0 ]; then
        $debug && echo "evaluating converted line"
        eval "echo \"$ELINE\"" >> "${tmpfile}.var"
      else
        echo -e "ERROR: both plain and converted lines evaluation failed for this line:\n\n$LINE\n\n"
        exit 1
      fi
    fi
    $debug && echo "  >> `tail -1 "${tmpfile}.var"`"
  done
}

find_source() {
  if [ -f "$from" ] ; then
    fullfrom=$from
  else
    if [ -f "$ROLES_ROOT/roles/$role/$flavor/files/$from" ] ; then
      fullfrom="$ROLES_ROOT/roles/$role/$flavor/files/$from"
    else
      if [[ "$flavor" != "common" ]] ; then
        if [ -f "$ROLES_ROOT/roles/$role/common/files/$from" ] ; then
          echo "file found under common flavor"
          fullfrom="$ROLES_ROOT/roles/$role/common/files/$from"
        else
          echo -n "not found ... "
          notfound=1
        fi
      else
        notfound=1
      fi
      if [ -n "$notfound" ] ; then
        echo -n "checking if another role is included ... "
        [ -n "$ROLEINCL" ] && echo -n "included role $ROLEINCL found ... "
        if [[ "$role" != "$ROLEINCL" ]] ; then
          if [ -f "$ROLES_ROOT/roles/$ROLEINCL/$flavor/files/$from" ] ; then
            fullfrom="$ROLES_ROOT/roles/$ROLEINCL/$flavor/files/$from"
            echo "file found in included role $ROLEINCL ... good"
            realrole=$ROLEINCL
          elif [ -f "$ROLES_ROOT/roles/$ROLEINCL/common/files/$from" ] ; then
            fullfrom="$ROLES_ROOT/roles/$ROLEINCL/common/files/$from"
            echo "file found in included role $ROLEINCL ... good"
            realrole=$ROLEINCL
          else
            echo "file $from not found, giving up"
            exit 1
          fi
        fi
        unset notfound
      fi
    fi
  fi

}

prepare_file() {
  [ -z "$tmpfile" ] && echo -e "\n*** Full path to the source file not found!\n\n" && exit 1
  if [ -f "$ROLES_ROOT/conf/$role.conf" ]; then
    store_vars "$ROLES_ROOT/conf/$role.conf"
  else
    echo "role config for $role not found!"
  fi
  [ -f "${tmpfile}.var" ] && source "${tmpfile}.var"
  rm -f "$tmpfile" "${tmpfile}.orig"
  cat "$fullfrom" | sed 's|}\%|}\%\\\n|g' | \
    sed "s|\\$|\\\\$|g;s|\%{\(.*\)}\%|$\{\1\}|g" | \
    sed 's|\\"|\\\\"|g' | \
    sed 's|"|\\\"|g' | \
    sed 's|`|\\\`|g' >> "${tmpfile}.orig"

  $debug && echo -e "\n --- TMP FILE ---\n\n" && cat "${tmpfile}.orig" && echo -e " --- END OF TMP FILE ---\n\n --- TMP FILE w/vars substituted ---\n\n"

  for LINE in `cat -E "${tmpfile}.orig"` ; do
    if [[ `echo $LINE | grep -c '\\\\$$'` -gt 0 ]]; then
      KEEP="${KEEP}`echo "$LINE" | sed 's|\\\\$$||'`"
      continue
    else
      LINE="${KEEP}`echo $LINE | sed 's|\$$||'`"
      unset KEEP
      a=`eval "echo \"$LINE\"" 2>>"$rpath/../logs/deploy.log"`
      if [ $? -eq 0 ] && [ -n "$a" ]; then
        echo "$a" >> "$tmpfile"
      else
        echo "$LINE" >> "$tmpfile"
      fi
      $debug && tail -1 "$tmpfile" || true
    fi
  done
  if [ -n "$role" -a -n "$task" -a -n "$timestamp" ] ; then
    install -d "$M_DEPL_WORK_DIR/${role}.${task}.${timestamp}/files"
    cp "$tmpfile" "$M_DEPL_WORK_DIR/${role}.${task}.${timestamp}/files/"
    cp "$tmpfile".{var,orig} "$M_DEPL_WORK_DIR/${role}.${task}.${timestamp}/files/"
  fi
}

[ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
SSH=`which ssh 2>/dev/null`
[ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
RSYNC=`which rsync 2>/dev/null`

possible_options="cluster help region verbose debug flavor role ip test dry cloud timestamp local"
# debug should be passed here as option only
unset debug

IFS1=$IFS
IFS='-'
for s_option in "$@"
do
  found=false
  case "$s_option" in
  --*=*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'`
    ;;
  --*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
    s_optarg='yes'
    ;;
  *=*)
    echo "Wrong syntax: options must start with a double dash"
    exit 1
    ;;
  *)
    [ -z "$from" ] && from="$s_option" || to="$s_option"
    found=true
    shift
    ;;
  esac
  for option in ${possible_options// /-} ; do
    [ "X$s_optname" == "X$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
  done
  if ! $found ; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done
IFS=$IFS1

if [ "X$help" == "Xyes" ] ; then
  cat <<"EOF"
Usage: ${0##*/} <options> <source path> <target path>"

Deploys files locally or to remote nodes. Substitutes variables marked as follows:
  
  %{VAR1}%

The list of target nodes is defined by either command-line arguments or environment variables.

Options:

  --local                  - deploys file locally.
  --cluster=clustername    - syncs to all nodes from this cluster.
                             Multiple clusters are allowed, separated by comma.
                             MUST be defined. To sync to all nodes, use 
                             --cluster=all. Accepts also M_CLUSTER environment
                             variable (from msh environment).
  --all                    - shortcut for --cluster=all.
  --ip=IP                  - ip for a single node operation.
                             If ip is defined, cluster and region are ignored.
  --region=region          - the command will be run on all nodes
                             from this region.
  --verbose                - shows each node details before running
                             the command.
  --debug                  - debug. Implies --verbose.

EOF
  exit 0
fi

([ -z "$from" ] || [ -z "$to" ]) && echo "Usage: ${0##*/} <options> <local path> <remote path>" && exit 1

[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../")
source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/conf/deploy.conf"

[ -n "$debug" ] && verbose="yes" && debug=true || debug=false
[ -n "$cloud" ] || cloud=$CLOUD
[ -z "$cluster" ] && cluster=$M_CLUSTER

if [ -z "$cloud" ]; then
  if [ -n "$ip" ]; then
    cloud=`grep "^$ip|" "$M_ROOT/nodes.list" | cut -sd'|' -f6`
  elif [ -n "$cluster" ]; then
    cloud=`grep "^$cluster|" "$M_ROOT/conf/clusters.conf" | cut -sd'|' -f12`
  fi
fi
[ -z "$cloud" ] && echo "No cloud found, check your configuration!" && exit 1

source "$M_ROOT/conf/clouds/${cloud}.conf"

export PATH="$M_ROOT/deploy:${M_ROOT}/cloud/${cloud}:${M_ROOT}/helpers:${PATH}"
[ -n "$SSHPORT" ] || SSHPORT=22

localip=`"$M_ROOT"/helpers/localips`
install -d "$M_TEMP/deploy/"
IFS1=$IFS
IFS='
'

[ -z "$role" ] && [ -n "$cluster" ] && role=`grep ^$cluster\| "$rpath/../conf/clusters.conf" | cut -d'|' -f10`
if [ -z "$cluster" ] ; then
  if [ -z "$role" ] ; then
    if [ -n "$M_ROLE" ] ; then
      role=$M_ROLE
      cluster=$M_CLUSTER
    fi
    # Still no cluster??
    if [ -z "$cluster" ] ; then
      echo "None of ip, role, cluster is defined."
      exit 1
    fi
  else
    cluster=`cat "$rpath/../conf/clusters.conf" | grep -vE "^[[:space:]]*$|^[[:space:]]*#" | cut -d'|' -f1,10 | grep \|${role}$ | cut -d'|' -f1`
    [ -z "$cluster" ] && echo "${rcommand}: cluster not defined for role $role" && exit 1
  fi
fi
([ -n "$all" ] || [ "$cluster" == "all" ]) && cluster=`cat "$rpath/../conf/clusters.conf" | grep -vE "^[[:space:]]*$|^[[:space:]]*#" | cut -d'|' -f1`
#[ `cat "${rpath}/../nodes.list" | grep -v ^$ | grep -v  ^# | grep -v ^[[:space:]]*# | cut -d'|' -f5 | grep -c "$cluster"` -eq 0 ] && [ -z "$test" -a -z "$dry" ] && echo "${rcommand}: no nodes found in cluster $cluster" && exit 1
[ -z "$flavor" ] && flavor=`cat "$rpath/../conf/clusters.conf" | grep -vE "^[[:space:]]*$|^[[:space:]]*#" | cut -d'|' -f10,11 | grep ^$role\| | cut -d'|' -f2`
[ -n "$verbose" ] && echo "### Reading configuration from $ROLES_ROOT/conf/$role.conf"

find_source
# fullfrom and realrole are now defined
tmpfile="$M_TEMP/deploy/`echo $fullfrom | tr '/' '_'`"
rm -f "$tmpfile" "${tmpfile}.orig" 2>/dev/null

[ -f "$ROLES_ROOT/conf/$role.conf" ] && store_vars "$ROLES_ROOT/conf/$role.conf"
# file prepared by deploy.run (useful if deploy_file is called from there)
[ -n "$VARFILE" ] && store_vars "$VARFILE"
## ROLEINCL - role of symlinked script or script defined in meta  from another
## role
## realrole - same as ROLEINCL, but when file to deploy is found in that role,
## not just script containing deploy_file
[ -n "$ROLEINCL" ] && [ -f "$ROLES_ROOT/conf/${ROLEINCL}.conf" ] && store_vars "$ROLES_ROOT/conf/${ROLEINCL}.conf"

if [ -z "$local" ]; then

  [ -n "$verbose" ] && echo "### Deploying file $from to $to"

  if [ -n "$test" ] || [ -n "$dry" ] ; then
    # some ip, just to fill the vars
    export ip="10.10.10.10"
    prepare_file
    cat "$tmpfile"
  else
    if [ -n "$ip" ] ; then
    # Single destination: region, cluster, cloud are ignored
      if [ `echo "$localip" | grep -c "^$ip$"` -ne 0 ] ; then
        prepare_file
        echo "${tmpfile##*/}...  "
        cp -up "$tmpfile" "$to" && echo "Success"
      else
        REGION=`cat "$rpath/../nodes.list" | grep ^$ip\| | cut -d'|' -f3`
        CLUSTER=`cat "$rpath/../nodes.list" | grep ^$ip\| | cut -d'|' -f5`
        if `"$M_ROOT"/helpers/mssh $ip test -d "$to"` ; then
          to=${to%/}/${from##*/}
        fi
        prepare_file
        cloudsync --ip=$ip "$tmpfile" "$to"
      fi
    else
    # Multiple destinations
      for cl in `echo -e $cluster | tr ',' '\n'` ; do
        for node in `cat "$rpath/../nodes.list" | grep -vE "^[[:space:]]*$|^[[:space:]]*#"` ; do
          IP=${node%%|*}
          if [ -n "$region" ] ; then
            REGION=`echo $node | cut -d'|' -f3`
            [ "_$REGION" == "_$region" ] || continue
          fi
          if [ -n "$cl" ] ; then
            CLUSTER=`echo $node | cut -d'|' -f5`
            [ "_$CLUSTER" == "_$cl" ] || continue
          fi
          if [ "_$verbose" == "_yes" ] ; then
            echo
            echo "### Node: $node"
            echo
          fi
          if [ `echo "$localip$" | grep -c "^$IP$"` -ne 0 ] ; then
            prepare_file
            echo "${tmpfile##*/}...  "
            cp -up "$tmpfile" "$to" && echo "Success"
          else
            if `"$M_ROOT"/helpers/mssh $IP test -d "$to"` ; then
              to=${to%/}/${from##*/}
            fi
            export ip=$IP
            prepare_file
            cloudsync --ip=$IP "$tmpfile" "$to"
          fi
        done
      done
    fi
  fi
else
  prepare_file
  echo "${tmpfile##*/}...  "
  if [ -d "$to" ] ; then
    to=${to%/}/${from##*/}
  fi
  mv "$tmpfile" "$to" && echo "Success"
fi
rm -f "$tmpfile"*
IFS=$IFS1
exit 0

