#!/bin/bash
# Copyright (C) 2008-2012 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rpath=$(readlink -f "$BASH_SOURCE")
rcommand="${rpath##*/}"
rpath="${rpath%/*}"
[ -n "$M_ROOT" ] || M_ROOT="${rpath%/*}"
#*/

possible_commands="help list clone create edit show"
possible_subcommands="list:metas,scripts,files,roles edit:meta,script,file show:meta,script,file"
possible_options="role cluster flavor method all strip"

printcol() {
  if [ -n "$1" ] ; then
    l=${#1}
    [[ $(($col-$l)) -le 0 ]] && l=$(($col-1))
    echo -n "$1"
    for ((i=0; i<$(($col-$l)); i++)) ; do
      echo -n " "
    done
  else
    for ((i=0; i<$col; i++)) ; do
      echo -n " "
    done
  fi
}

declare -i ppn
ppn=1

commfound=false
subcommfound=false

IFS1=$IFS
IFS='-'
for s_option in "$@"
do
  found=false
  case $s_option in
  --*=*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'`
    ;;
  --*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
    s_optarg='yes'
    ;;
  *=*)
    echo "Wrong syntax: options must start with a double dash"
    exit 1
    ;;
  *)
    s_param=$s_option
    s_optname=''
    s_optarg=''
    case $ppn in
      1)
        for comm in ${possible_commands// /-}; do
          if [ "X$s_param" == "X$comm" ]; then
            if $commfound ; then
              echo "Only one command can be executed!"
              echo "Commands are: $possible_commands"
              exit 1
            else
              found=true
              commfound=true
            fi
          fi
        done
        if ! $found ; then 
          echo "Unknown command: $s_param"
          exit 1
        fi
        command1=$s_param
        ;;
      2)
        for subcomm in ${possible_subcommands// /-}; do
          [ "X${subcomm%%:*}" == "X$command1" ] && subcommands=${subcomm#*:}
          for sub in ${subcommands//,/-}; do
            if [ "X$s_param" == "X$sub" ]; then
              if $subcommfound ; then
                echo "Only one subcommand can be executed!"
                echo "Subcommands for $command1 are: ${subcommands}"
                exit 1
              else
                found=true
                subcommfound=true
              fi
            fi
          done
          unset subcommands
        done
        if ! $found ; then 
          param1=$s_param
        else
          command2=$s_param
        fi
        ;;
      3)
        if [ -z "$param1" ] ; then
          param1=$s_param
        else
          param2=$s_param
        fi
        ;;
      4)
        if [ -z "$param2" ] ; then
          param2=$s_param
        else
          echo "Wrong number of positional parameters!"
          exit 1
        fi
        ;;
      *)
        echo "Wrong number of positional parameters!"
        exit 1
        ;;
    esac
    shift
    ppn+=1
    ;;
  esac
  for option in `echo $possible_options | sed 's| |-|g'`; do
    if [ "X$s_optname" == "X$option" ]; then
      if [ -n "$s_optarg" ]; then
        eval "$s_optname=\"$s_optarg\""
      else
        [ -z "$(eval echo \$$option)" ] && eval "$option="
      fi
      found=1
    fi
  done
done

if [ -n "$role" ]; then
  if [ `cat "$M_ROOT/conf/clusters.conf" | cut -d'|' -f10 | grep "^$role$" | wc -l` -eq 0 ]; then
    echo "Warning: unable to associate a cluster with this role ($role). Some functions may not work correctly, and you'll have to define flavor either using option --flavor or as an environment variable."
  fi
fi

if [ "X$command1" == "Xclone" ]; then 
  [ -z "$method" ] && echo -e "Using default method: copy\n    (other available methods are: symlink, copywithlinks - see 'role --help' for details)"
  case $method in
    copy|cp)
      methodcommand=`which cp 2>/dev/null` ; methodcommand="`echo -e "$methodcommand\n-u\n-L"`"
      ;;
    link|symlink)
      methodcommand=`which ln 2>/dev/null` ; methodcommand="`echo -e "$methodcommand\n-s"`"
      ;;
    copywithlinks|cpwithlinks)
      methodcommand=`which cp 2>/dev/null` ; methodcommand="`echo -e "$methodcommand\n-u\n-d"`"
      ;;
  esac
fi

IFS='
'
case $command1 in
  list)
    case $command2 in
      metas)
        [ -z "$param1" ] && param1="$role"
        [ -z "$param1" ] && echo "Role is empty" && exit 1
        COL=`tput cols 2>/dev/null`
        [ -n "$COL" ] && col=$((COL/3+4)) || col=${col-30}
        printcol "Meta"
        printcol "Scripts"
        echo "Includes"
        for m in `ls -1 "$ROLES_ROOT/$param1" | grep ^meta\. | sed 's|^meta.||'` ; do
          ml=`cat "$ROLES_ROOT/$param1/meta.$m" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]#`
          sn=`echo "$ml" | wc -l`
          for sc in $ml ; do
            scf="${sc#* }" ; scf=`eval "echo \"$scf\""`
            [ -e "$ROLES_ROOT/$scf" ] || scerr+=(" *** Script \"$ROLES_ROOT/$scf\" not found")
          done
          in=`echo "$ml" | awk '{print $2}' | cut -d'/' -f1 | sort | uniq | grep -v '^${role}$' | grep -v '^$role$' | grep -v "^$param1$"`
          if [ -z "$in" ] ; then
            printcol "$m"
            echo "$sn"
          else
            for ins in $in ; do
              printcol "$m"
              printcol "$sn"
              echo "$ins"
              unset m sn
            done
          fi
          for ((i=0; i<${#scerr[*]}; i++)) ; do
            [ -n "$M_COLOR" ] && echo -n -e "$CONTR_SEQ$FG_RED"
            echo "${scerr[$i]}"
            [ -n "$M_COLOR" ] && echo -n -e "$UNSET_COLOR"
          done
          unset scerr
        done
      ;;
      scripts)
        [ -z "$param1" ] && param1="$role"
        [ -z "$param1" ] && echo "Role is empty" && exit 1
        COL=`tput cols 2>/dev/null`
        [ -n "$COL" ] && col=$((COL/3+4)) || col=${col-30}
        printcol "Script"
        printcol "Meta"
        echo "Role"
        for sc in `find "$ROLES_ROOT/$param1/$flavor/" -maxdepth 1 -type f -o -type l` `find "$ROLES_ROOT/$param1/common/" -maxdepth 1 -type f -o -type l`; do
          scr="${sc/$ROLES_ROOT\//}" && scr="${scr/$param1\//}"
          for m in `ls -1 "$ROLES_ROOT/$param1" | grep ^meta\.` ; do
            [ `grep -c "${sc##*/}$" "$ROLES_ROOT/$param1/$m"` -gt 0 ] && mi+=( "${m#meta.}" )
          done
          
          [ -z "$mi" ] && mi="unused"
          for mis in ${mi[*]} ; do
            if [ "$mis" == "unused" ] ; then
              if [ -n "$all" ]; then
                [ -n "$M_COLOR" ] && echo -n -e "$CONTR_SEQ$FG_MAGENTA"
                printcol "$scr"
                echo "not found in any meta"
                [ -n "$M_COLOR" ] && echo -n -e "$UNSET_COLOR"
                unset scr
              fi
            else
              for r in `grep "${sc##*/}" "$ROLES_ROOT/$param1/meta.$mis" | awk '{print $2}' | cut -d'/' -f1 | sort | uniq` ; do
                r=`eval "echo \"$r\""`
                printcol "$scr"
                printcol "$mis"
                echo "$r"
                unset scr mis
              done
            fi
          done
          if [ -n "$all" ]; then
            for or in `find "$ROLES_ROOT" -mindepth 1 -maxdepth 1 -type d ! -name "$param1"` ; do
              [ `cat "$or/"meta.* 2>/dev/null | grep -c "${sc##*/}$"` -gt 0 ] && ori+=( "found in role ${or##*/}" )
            done
            for oris in ${ori[*]} ; do
              printcol "$scr"
              printcol "$oris"
              echo
              unset scr oris
            done
            unset ori
          fi
          unset mi
        done
      ;;
      files)
        [ -z "$param1" ] && param1="$role"
        [ -z "$param1" ] && echo "Role is empty" && exit 1
        COL=`tput cols 2>/dev/null`
        [ -n "$COL" ] && col=$((COL/3+4)) || col=${col-30}
        printcol "File"
        echo "Script"
        for fl in `find "$ROLES_ROOT/$param1/$flavor/files/" -maxdepth 1 -type f -o -type l` `find "$ROLES_ROOT/$param1/common/files/" -maxdepth 1 -type f -o -type l` ; do
          for sc in `find "$ROLES_ROOT/$param1/$flavor/" -maxdepth 1 -type f -o -type l` ; do
            [ -n "`grep -E "deploy_file|cloudsync|cp|scp|rsync" "$sc" | grep "${fl##*/}"`" ] && sci="$sci $flavor/${sc##*/}"
          done
          if [ -n "$sci" ]; then
            for scis in $sci ; do
              printcol "${fl##*/}"
              echo "$scis"
              unset fl
            done
          elif [ -n "$all" ]; then
            printcol "${fl##*/}"
            echo "not found in any script"
            unset fl
          fi
          unset sci
        done
      ;;
      roles|'')
        COL=`tput cols 2>/dev/null`
        [ -n "$COL" ] && col=$((COL/3-4)) || col=${col-20}
        printcol "Role"
        printcol "Cluster"
        printcol "Flavor"
        echo "Image"
        for r in `find $ROLES_ROOT/ -maxdepth 1 -type d` ; do
          r=${r##*/}
          [[ $r =~ '^\.' ]] && continue
          for cl in `cat $M_ROOT/conf/clusters.conf | cut -d'|' -f1,10 | grep \|${r}$ | cut -d'|' -f1` ; do
            printcol "$r"
            printcol "$cl"
            ln=`cat "$M_ROOT/conf/clusters.conf" | grep "^$cl"`
            fl=`echo "$ln" | cut -d'|' -f11`
            printcol "$fl"
            im=`echo "$ln" | cut -d'|' -f6`
            echo "$im"
            unset r
          done
          [ -n "$r" ] && echo "$r"
        done
      ;;
      *)
      echo -e "Usage: $rcommand list <metas|scripts|files|roles> <--all>\n"
      ;;
    esac
    ;;
  clone)
    [ -z "$param1" -o -z "$param2" ] && echo "Usage: role clone SOURCE TARGET" && exit 1
    if [ ! -d "$ROLES_ROOT/$param1" ]; then
      if [ ! -d "$param1" ]; then
        echo "Role $param1 not found" && exit 1
      else
        sourcerole="$param1"
      fi
    else
      sourcerole="$ROLES_ROOT/$param1"
    fi
    if [ -d "$ROLES_ROOT/$param2" ]; then
      if [ $(cd -P "$ROLES_ROOT/$param2/../" && pwd) == "$ROLES_ROOT" ]; then
        echo "Role $param2 exists, adding files missing in the target role. Use --all to overwrite existing files."
      else
        echo "Role folder must be a subfolder of ${ROLES_ROOT}. You can change ROLE_ROOT setting in conf/deployment.conf"
        exit 1
      fi
    fi
    for dir in `find "$sourcerole/" -type d` ; do
      newdir=`echo "$dir" | sed "s|^$sourcerole/||"`
      install -d "$ROLES_ROOT/$param2/$newdir"
    done
    for sl in `find "$sourcerole/" -type l` ; do
      nsl=`echo "$sl" | sed "s|$sourcerole/||"`
      f=`readlink $sl`
      if [ "X${f:0:1}" == "X/" ]; then
        if [ "$method" == "link" ]; then
          if [ ! -e "$ROLES_ROOT/$param2/$nsl" -o -n "$all" ]; then
            echo "${sl##*/} is a symlink resolving to an absolute path. Copying the file instead."
            cp -u "$f" "$ROLES_ROOT/$param2/$nsl"
          fi
        fi
      else
        if [ -e "$ROLES_ROOT/$param2/$nsl" -a ! -h "$ROLES_ROOT/$param2/$nsl" ]; then
          echo "Source file $nsl is a symlink, but target exists and is not a symlink. Skipping."
        else
          if [ ! -e "$ROLES_ROOT/$param2/$nsl" -o -n "$all" ]; then
            $methodcommand "$sl" "$ROLES_ROOT/$param2/$nsl"
          fi
        fi
      fi
    done
    for f in `find "$sourcerole/" -type f ! -name role.conf` ; do
      nf=`echo "$f" | sed "s|$sourcerole/||"`
      if [ ! -e "$ROLES_ROOT/$param2/$nf" -o -n "$all" ]; then
        $methodcommand "$f" "$ROLES_ROOT/$param2/$nf"
      fi
    done
    if [ ! -e "$ROLES_ROOT/$param2/role.conf" ]; then
      for rcl in `cat "$sourcerole/role.conf"` ; do
        echo "$rcl" | sed 's|=|=  #|' >> "$ROLES_ROOT/$param2/role.conf"
      done
    fi
    ;;
  create)
    declare -a flarr
    [ -n "$param2" ] && echo "Usage: role create NAME" && exit 1
    [ -z "$param1" ] && echo "Usage: role create NAME" && exit 1
    for fl in `find "$ROLES_ROOT/"*/ -maxdepth 1 -type d | sed "s|^$ROLES_ROOT/||" | cut -d '/' -f2 | sort | uniq | grep -v ^$` ; do
      flarr+=( "$fl" )
    done
    echo -e "\nChoose existing system flavors from the list and/or add new ones. Existing flavors can be added by their numbers.\n\nExample: 2,4,5,centos6    - will add existing flavors with numbers 2, 4 and 5 and create a new one named centos6\n\nTo have all listed flavors in the new role just press Enter\n\n"
    for ((i=0; i<${#flarr[*]}; i++)) ; do
      echo "$((i+1)). ${flarr[$i]}"
    done
    echo
    read -p "Input flavors, separated by comma: " roleslist
    if [ -z "$roleslist" ] ; then
      for fl in ${flarr[*]} ; do
        install -d "$ROLES_ROOT/$param1/$fl"
      done
    else
      for r in `echo -e "$roleslist" | sed 's|,|\n|g'` ; do
        if [[ $r =~ ^[[0-9]]* ]]; then
          install -d "$ROLES_ROOT/$param1/${flarr[$r-1]}/files"
        else
          install -d "$ROLES_ROOT/$param1/$r/files"
        fi
        install -d "$ROLES_ROOT/$param1/common/files"
      done
    fi
    echo -e '# Here come the variables, shell format, e.g.:\n# VAR=value\n' > "$ROLES_ROOT/$param1/role.conf"
    ;;
  edit)
    [ -z "$param1" ] && echo "Usage: role edit meta|script|file NAME" && exit 1
    [ -n "$VISUAL" ] && ED=$VISUAL
    [ -z "$ED" -a -n "$EDITOR" ] && ED=$EDITOR
    [ -z "$ED" ] && echo "Using vim as text editor. Set VISUAL or EDITOR environment variable to another editor if you want" && ED=`which vim 2>/dev/null`
    [ -z "$ED" ] && echo "Editor not found" && exit 1
    case $command2 in
      meta)
        [ ! -e "$ROLES_ROOT/$role/meta.$param1" ] && "Meta $param1 doesn't exist in this role (${role})." && exit 1
        $ED "$ROLES_ROOT/$role/meta.$param1"
        ;;
      script)
        prmarr=( `echo "$param1" | tr '/' '\n'` )
        [ ${#prmarr[*]} -gt 3 ] && echo "Path can't have more than 3 parts (role/flavor/script)" && exit 1
        case ${#prmarr[*]} in
          3) $ED "$ROLES_ROOT/${prmarr[0]}/${prmarr[1]}/${prmarr[2]}" ;;
          2) $ED "$ROLES_ROOT/$role/${prmarr[0]}/${prmarr[1]}" ;;
          1)
          if [ ! -e "$ROLES_ROOT/$role/$flavor/$param1" ]; then
            if [ ! -e "$ROLES_ROOT/$role/common/$param1" ]; then
              echo "$param1 doesn't exist in this role. `[[ "$flavor" == "common" ]] && echo "Flavor 'common' has been" || echo "Flavors '$flavor' and 'common' have been"` searched. Use options --role= and --flavor= to search in other roles and flavors. If it is a new script, use full notation (role/flavor/scriptname) or create it directly: $ED \"$ROLES_ROOT/$role/$flavor/$param1\" or $ED \"$ROLES_ROOT/$role/common/$param1\"." && exit 1
            else
              $ED "$ROLES_ROOT/$role/common/$param1"
            fi
          else
            $ED "$ROLES_ROOT/$role/$flavor/$param1"
          fi
          ;;
        esac
        ;;
      file)
        if [ -h "$ROLES_ROOT/$role/$flavor/files/$param1" ]; then
          rf=`readlink -f "$ROLES_ROOT/$role/$flavor/files/$param1"`
        elif [ -h "$ROLES_ROOT/$role/common/files/$param1" ]; then
          rf=`readlink -f "$ROLES_ROOT/$role/common/files/$param1"`
        else
          rf="$ROLES_ROOT/$role/$flavor/files/$param1"
        fi
        [ ! -e "$rf" ] && rf="$ROLES_ROOT/$role/common/files/$param1"
        [ ! -e "$rf" ] && echo "File $param1 doesn't exist in this role. Flavors $flavor and common have been searched. Use options --role= and --flavor= to search in other roles and flavors. If you intended to create a new file, just create it directly: $ED \"$ROLES_ROOT/$role/$flavor/files/$param1\" or $ED \"$ROLES_ROOT/$role/common/files/$param1\"." && exit 1
        if [ `file "$rf" | cut -d':' -f2 | grep -c text` -eq 1 ]; then
          $ED "$rf"
        else
          echo "The file seems binary, sorry. Open it directly if you are certain."
        fi
        ;;
      *)
        echo "Usage: role edit meta|script|file NAME"
        ;;
    esac
    ;;
  show)
    [ -z "$param1" ] && echo "Usage: role show meta|script|file NAME" && exit 1
    case $command2 in
      meta)
        [ ! -e "$ROLES_ROOT/$role/meta.$param1" ] && "Meta $param1 doesn't exist in this role (${role})." && exit 1
        [ -n "$strip" ] && cat "$ROLES_ROOT/$role/meta.$param1" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]# || cat "$ROLES_ROOT/$role/meta.$param1"
        ;;
      script)
        prmarr=( `echo "$param1" | tr '/' '\n'` )
        [ ${#prmarr[*]} -gt 3 ] && echo "Path can't have more than 3 parts (role/flavor/script)" && exit 1
        case ${#prmarr[*]} in
          3) [ -n "$strip" ] && cat "$ROLES_ROOT/${prmarr[0]}/${prmarr[1]}/${prmarr[2]}" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]# || cat "$ROLES_ROOT/${prmarr[0]}/${prmarr[1]}/${prmarr[2]}" ;;
          2) [ -n "$strip" ] && cat "$ROLES_ROOT/$role/${prmarr[0]}/${prmarr[1]}" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]# || cat "$ROLES_ROOT/$role/${prmarr[0]}/${prmarr[1]}" ;;
          1)
          if [ ! -e "$ROLES_ROOT/$role/$flavor/$param1" ]; then
            if [ ! -e "$ROLES_ROOT/$role/common/$param1" ]; then
              echo "$param1 doesn't exist in this role. `[[ "$flavor" == "common" ]] && echo "Flavor 'common' has been" || echo "Flavors '$flavor' and 'common' have been"` searched. Use options --role= and --flavor= to search in other roles and flavors." && exit 1
            else
              [ -n "$strip" ] && cat "$ROLES_ROOT/$role/common/$param1" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]# || cat "$ROLES_ROOT/$role/common/$param1"
            fi
          else
            [ -n "$strip" ] && cat "$ROLES_ROOT/$role/$flavor/$param1" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]# || cat "$ROLES_ROOT/$role/$flavor/$param1"
          fi
          ;;
        esac
        ;;
      file)
        if [ -h "$ROLES_ROOT/$role/$flavor/files/$param1" ]; then
          rf=`readlink -f "$ROLES_ROOT/$role/$flavor/files/$param1"`
        elif [ -h "$ROLES_ROOT/$role/common/files/$param1" ]; then
          rf=`readlink -f "$ROLES_ROOT/$role/common/files/$param1"`
        else
          rf="$ROLES_ROOT/$role/$flavor/files/$param1"
        fi
        [ ! -e "$rf" ] && rf="$ROLES_ROOT/$role/common/files/$param1"
        [ ! -e "$rf" ] && echo "File $param1 doesn't exist in this role. Flavors $flavor and common have been searched. Use options --role= and --flavor= to search in other roles and flavors." && exit 1
        if [ `file "$rf" | cut -d':' -f2 | grep -c text` -eq 1 ]; then
          [ -n "$strip" ] && cat "$rf" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]# || cat "$rf"
        else
          file "$rf"
        fi
        ;;
      *)
        echo "Usage: role show meta|script|file NAME"
        ;;
    esac
    ;;
  help)
    cat <<"EOF"

Syntax: role command <sub-command> <args> <--option=value>

  list            - lists all existing roles and some info about them:
                      Cluster: the default cluster for this role
                      Flavor: Linux flavor, default for this role
                      Image: server image ID (if cloud environment is set)
  
    list metas    - lists all metascripts for the current role or the role set
                    with the --role option and additional info:
                      Scripts: the number of scripts included in this meta
                      Includes: lists other roles which this meta includes
                                  scripts from
    list scripts  - lists all scripts (not only included in metas) for the role
                    along with the meta they are included into
    list files    - lists all files for the role along with the scripts they are
                    mentioned in
                    
  create          - creates a new role
EOF
    ;;
  *)
  
    ;;
esac

IFS=$IFS1
