#!/bin/bash

[ -h $0 ] && xcommand=`readlink $0` || xcommand=$0
rcommand=${xcommand##*/}
rpath=${xcommand%/*}
fpath=$(cd "$rpath" && pwd)
#*/

if [ $# -eq 0 ] ; then
  if [ -d "${rpath}/../rc" ] ; then
    for sl in ${rpath}/../rc/* ; do
      [ "X$(cd `readlink $sl 2>/dev/null` && pwd)" == "X${fpath}" ] && rm -f $sl
    done
  fi
else
  if [ -d "${rpath}/rc" ] ; then
    rm -f ${rpath}/rc/*${1}
  fi
fi
