#!/bin/bash
# Copyright (C) 2008-2014 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/

CURL=`which curl 2>/dev/null`
CURL="$CURL -s -k"
V="2"

GNTI=`which gnt-instance 2>/dev/null`

possible_options="cloud id name ip return verbose cluster help updatelist quick slow"
necessary_options=""

ARGV=`echo $@ | sed 's/^--//;s/ --/|/g;s/ /|/g'`
[ -z "$ARGV" ] && ${0} --help
IFS1=$IFS
IFS='|'
for s_option in $ARGV
do
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "_$s_optarg" == "_$s_optname" ] && s_optarg="yes"
  found=false
  for option in `echo $possible_options | sed 's/ /|/g'`; do 
    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true
  done
  if ! $found ; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done
IFS=$IFS1

find_by_ip() {
  [ -z "$1" ] && return 1
  if [ -f "$M_TEMP/show_nodes.resp" ] ; then
    sn=`grep "\"addresses\"" "$M_TEMP/show_nodes.resp" | grep "\"${1}\"$" | cut -d'/' -f3`
    id=`grep "/$sn/\"id\"|" "$M_TEMP/show_nodes.resp" | cut -d'|' -f2`
  fi
  if [ -z "$name" ]; then
    name=`IAMACHILD=1 "$rpath"/show_nodes --cloud=$CLOUD --forceupdate --view=table | grep "|$1|" | cut -d'|' -f1`
  fi
  [ -z "$name" ] && name=`cat "$M_ROOT/cloud/${CLOUD}.list" | grep "|\"${1}\"|" | cut -d'|' -f1`
  if [ -z "$name" ]; then
    log "unable to identify this node by its IP"
    sed -i "/^${1}.*${CLOUD}$/d" "$M_ROOT/nodes.list"
  fi
}

list_the_cluster() {
  # 1. compile full list
  # 2. if 'slow' is set, verify each node by querying its personal details
  ips1=`cat "$M_ROOT/nodes.list" | grep \|${CLOUD}$ | cut -d'|' -f1,5 | grep \|${cluster}$ | cut -d'|' -f1`
  if [ "_$NETWORK" == "_external" ]; then
    ips2=`cat "$M_ROOT/cloud/${CLOUD}.list" 2>/dev/null | grep -E "\|\"${cluster}\"\||\|\"${cluster}\"$" | cut -d'|' -f6 | tr -d '"'`
  else
    ips2=`cat "$M_ROOT/cloud/${CLOUD}.list" 2>/dev/null | grep -E "\|\"${cluster}\"\||\|\"${cluster}\"$" | cut -d'|' -f7 | tr -d '"'`
  fi
  ips=`echo -e "$ips1\n$ips2" | grep -v ^$ | sort | uniq`

  if [ -z "$quick" ]; then
    for ip in `echo "$ips"` ; do
      if [ -n "$ip" ]; then
        nodedetails=`IAMACHILD=1 "$M_ROOT"/cloud/common/get_node_details --cloud=$CLOUD --ip=$ip 2>/dev/null`
        name="`echo "$nodedetails" | grep '^0/"name"|' | cut -s -d'|' -f2 | tr -d '"'`"
        if [ -n "$name" ]; then
          if [ -z "`echo "$nodedetails" | grep -i '"UUID"|'`" ]; then
            sed -i "/^${ip}.*${CLOUD}$/d" "$M_ROOT/nodes.list"
            sed -i "/|${ip}|/d" "$M_ROOT/cloud/${CLOUD}.list"
          else
            grep -q "|${ip}|" "$M_ROOT/cloud/${CLOUD}.list" || $GNTI list --separator='|' --no-headers -o "name,status,nic.ip/0,nic.ips,disk.sizes,be/memory,be/vcpus,pnode,snodes,tags,uuid,os,ctime" "$name" >> "$M_ROOT/cloud/${CLOUD}.list"
            if ! `grep -q "^${ip}|" "$M_ROOT/nodes.list"` ; then
              cluster="`echo "$nodedetails" | grep "\"tags\"/" | grep "\"${CLUSTER_TAG}:" | cut -s -d'|' -f2 | tr -d '"' | cut -s -d':' -f2`"
              key="`grep "^$cluster|" "$M_ROOT/conf/clusters.conf" | cut -s -d'|' -f2 | tr -d '"'`"
              echo "$ip|$key||$name|$cluster|$CLOUD" >> "$M_ROOT/nodes.list"
            fi
          fi
        fi
      fi
    done
  else
    if [ -z "$ips2" ]; then
      if [ -n "$ips1" ]; then
        for ip in $ips1 ; do
          log "IP $ip is present in the nodes list but not in the cloud list, adding to the cloud list"
          $GNTI list --separator='|' --no-headers -o "name,status,nic.ip/0,nic.ips,disk.sizes,be/memory,be/vcpus,pnode,snodes,tags,uuid,os,ctime" `IAMACHILD=1 "$M_ROOT"/cloud/common/get_node_details --cloud=$CLOUD --ip=$ip 2>/dev/null | grep '^0/"name"|' | cut -s -d'|' -f2 | tr -d '"'` >> "$M_ROOT/cloud/${CLOUD}.list"
        done
      fi
    fi
  fi
  cat "$M_ROOT/cloud/${CLOUD}.list" | grep -E "\|cluster:${cluster}\||\|cluster:${cluster}$"
}

found=0
for option in `echo $necessary_options | sed 's/,//g'`; do
  [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options}, --${option}" && found=1
done
if [[ $found -eq 1 ]]; then
  missing_options=${missing_options#*,}
  echo "Necessary options: $missing_options not found"
  exit 1
fi

[ -n "$help" ] && cat << "EOF"

Finds and lists node(s) in Ganeti-based private clouds

Usage: $rcommand <options>

Options:

  --ip=[ip]                     - finds a node by its IP
  
  --name=[node name]          - finds node(s) by name
  
  --cluster=[cluster name]      - finds all nodes in this cluster
                                  (see also --fast and --slow below).
                                  If either of ip/name/id is provided, this
                                  option is ignored, and the search becomes
                                  non-cluster one
  
  --cloud=[cloud name]          - must be provided for any of the searches
                                  above; can be provided either via command-line
                                  option or via environment variable CLOUD;
                                  command-line option has higher priority
                                  
  --fast                        - for cluster search, checks only provider-
                                  specific list (cloud/rackspace.list)
                                  
  --slow                        - for cluster search, gets details for each
                                  node in this cloud listed in nodes.list
                                  and cloud/rackspace.list from the cloud API
                                  and does its best to fix any inconsistencies
                                  found
                                  
  --updatelist                  - updates nodes.list with nodes found
                                  (applicable only to non-cluster search)
  
                                  
EOF

[ -n "$cloud" ] && CLOUD=$cloud
export CLOUD
[ -n "$fast" -a -n "$slow" ] && echo "both --fast and --slow options are set, not sure what to do" && exit 1

source "$rpath/../../conf/mon.conf"
[ -n "$CLOUD" ] && source "$rpath/../../conf/clouds/${CLOUD}.conf"
source "$rpath/../../lib/cloud_functions.sh"
M_TEMP="$M_TEMP/cloud/$CLOUD"

if [ -z "$IAMACHILD" ]; then
  lock_cloudops || exit 10
fi

if [ -z "$name" ]; then

  if [ -z "$ip" ]; then
    if [ -z "$cluster" ]; then
      echo "One of ip, name or cluster is required to identify the node"
      proper_exit 1 166
    else
      list_the_cluster
      proper_exit 0 169
    fi
  else
    find_by_ip $ip
  fi
else
  # ip must be present in nodes.list, so it's simple
  ip=`cat "$rpath/../../nodes.list" | grep -vE "^#|^[[:space:]]#" | cut -d'|' -f1,4,6 | grep -v ^$ | grep "|${CLOUD}$" | grep "|${name}|" | cut -d'|' -f1`
  if [ -n "$ip" ]; then
    find_by_ip $ip
  fi
fi
[ -z "$name" ] && echo "Unable to identify this node" && proper_exit 1 180

req="/$V/instances/$name"

request() {
  $CURL -X GET "https://${GANETI_APIURL}$req" | "$M_ROOT/lib/json2txt" > "$M_TEMP/${rcommand}.resp"
}

request

if [ `grep -c ^0\/\"code\"\|404$ "$M_TEMP/${rcommand}.resp"` -eq 1 ] ; then
  echo "Node $name does not exist" && proper_exit 1 191
fi

if [ -n "$updatelist" ]; then
  nodedetails="`cat "$M_TEMP/${rcommand}.resp"`"
  if [[ "$NETWORK" == "external" ]]; then
    ip="`echo "$nodedetails" | grep '/"addresses"/"public"/0|' | cut -s -d'|' -f2 | tr -d '"'`"
  else
    ip="`echo "$nodedetails" | grep '/"addresses"/"private"/0|' | cut -s -d'|' -f2 | tr -d '"'`"
  fi
  if ! `grep -q "^${ip}|" "$M_ROOT/nodes.list"` ; then
    name="`echo "$nodedetails" | grep '"name"|' | cut -s -d'|' -f2 | tr -d '"'`"
    cluster="`echo "$nodedetails" | grep '"metadata"/"cluster"|' | cut -s -d'|' -f2 | tr -d '"'`"
    key="`grep "^$cluster|" "$M_ROOT/conf/clusters.conf" | cut -s -d'|' -f2 | tr -d '"'`"
    echo "$ip|$key||$name|$cluster|$CLOUD" >> "$M_ROOT/nodes.list"
  fi
else
  cat "$M_TEMP/${rcommand}.resp"
fi

proper_exit 0 211

