#!/bin/bash

# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


rcommand=${0##*/}
rpath=${0%/*}
#*/ (this is needed to fix vi syntax highlighting)
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
QEMU_IMG=`which qemu-img 2>/dev/null`
[ -z "$QEMU_IMG" ] && echo "qemu-img utility is not found" >&2 && exit 1
possible_options="name ip id imagename help verbose"
necessary_options=""
IFS1=$IFS
IFS='--'
for s_option in "${@}"
do
  found=0
  case ${s_option} in
  --*=*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'` 
    ;;
  --*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
    s_optarg='yes' 
    ;;
  *=*)
    echo "Wrong syntax: options must start with a double dash"
    exit 1
    ;;
  *)
    s_param=${s_option}
    s_optname=''
    s_optarg=''
    ;;
  esac
  for option in `echo $possible_options | sed 's/ /--/g'`; do
    if [ "X$s_optname" == "X$option" ]; then
      if [ -n "$s_optarg" ]; then
        eval "$s_optname=\"$s_optarg\""
      else
        [ -z "$(eval echo \$$option)" ] && eval "$option="
      fi
      found=1
    fi
  done
  [ "X$s_option" == "X$s_param" ] && found=1
  if [[ $found -ne 1 ]]; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
  [ -n "$s_param" ] && params="$params $s_param" && unset s_param
done
IFS=$IFS1
if [ "X$help" == "Xyes" ] ; then
  cat <<"EOF"
Usage: ${0##*/} <options> or ${0##*/} <options> [image name]

Image name can be defined as a long-option --imagename or as a positional parameter

Options:

  --name=NAME              - name of the source instance
  --ip=IP                  - ip of the source instance
  --id=NAME                - for compatibility; same as name in Ganeti
  --cluster=CLUSTER        - save under name of the base image of this cluster
                             (as defined in conf/clusters.conf)
  --verbose                - shows some additional details
  --help                   - this help
  
EOF
  exit 0
fi

source "$M_ROOT/conf/cloud.conf"
source "$M_ROOT/conf/mon.conf"
[ -z "$M_TEMP" ] && M_TEMP="/tmp/m_script"
M_TEMP="$M_TEMP/cloud/ganeti"
[ -d "$M_TEMP" ] || install -d "$M_TEMP"

if [ -z "$imagename" ]; then
  if [ -n "$cluster" ]; then
    imagename=`cat "$M_ROOT/conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f5 | cut -d'+' -f1`
  else
    [ -z "$imagename" ] && imagename="$params"
  fi
fi
[ -z "$imagename" ] && log "image name is mandatory, not saving" && exit 1


  


