#!/bin/bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$M_ROOT/conf/mon.conf"
[ -n "$cloud" ] && CLOUD=$cloud
[ -z "$CLOUD" ] && echo "No cloud defined" && exit 1
[ -z "$M_TEMP" ] && echo "M_TEMP is not defined" && exit 1

source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/conf/clouds/${CLOUD}.conf"
source "$M_ROOT/lib/cloud_functions.sh"

[ -n "$update_servers_list" -a -n "$filter" ] && echo "Impossible options combination" && exit 1
M_TEMP="$M_TEMP/cloud/$CLOUD"
[ -d "$M_TEMP" ] || install -d "$M_TEMP"

declare -i icount

GNTI=`which gnt-instance 2>/dev/null`
[ -z "$GNTI" ] && log "ERROR: gnt-instance utility not found" && exit 1

export IAMACHILD M_TEMP CLOUD

possible_options="cloud cluster state filter node view all count update_servers_list forceupdate noupdate resolveids"
necessary_options=""

ARGV=`echo ${@} | sed 's/^--//' | sed 's/ --/|/g'`

IFS1=$IFS
IFS='|'
for s_option in $ARGV
do
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "_$s_optarg" == "_$s_optname" ] && s_optarg="yes"
  found=false
  for option in `echo $possible_options | sed 's/ /|/g'`; do 
    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true
  done
   if ! $found ; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done
IFS=$IFS1

found=0
for option in `echo $necessary_options | sed 's/,//g'`; do
  [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options}, --${option}" && found=1
done
if [[ found -eq 1 ]]; then
  missing_options=${missing_options#*,}
  echo "Necessary options: $missing_options not found"
  exit 1
fi

[ -n "$update_servers_list" ] && [ -n "$filter" ] && echo "Impossible options combination" && exit 1
[ -n "$forceupdate" ] && rm -f "$M_TEMP"/${rcommand}.resp
[ -z "$state" -a -n "$status" ] && state=$status
[ -z "$state" ] && state="running"
[ -n "$filter" ] && filter="${filter},nic_ips,cluster"
[ -n "$update_servers_list" ] && [ -f "$M_ROOT/cloud/servers.list.${CLOUD}" ] && rm "$M_ROOT/cloud/servers.list.${CLOUD}"

PARS="name,status,nic.ip/0,nic.ips,disk.sizes,be/memory,be/vcpus,pnode,snodes,tags,uuid,os,ctime"
PARR=( `echo "$PARS" | tr './' '_' | tr ',' ' '` )

request() {
  $GNTI list --separator='|' --no-headers -o $PARS > "$M_TEMP/${rcommand}.resp"
}

list_servers() {
  IFS1=$IFS
  IFS='
'
  if [ -f "$M_TEMP/${rcommand}.resp" ] ; then

    for LINE in `cat "$M_TEMP/${rcommand}.resp"` ; do
      
      LARR=( `echo -e "$LINE" | sed 's/^/"/;s/$/"/' | sed 's/|/"\n"/g'` )
      
      for ((i=0; i<=${#PARR[*]}; i++)); do
        #[ -n "${PARR[$i]}" ] && echo "${PARR[$i]}=${LARR[$i]}"
        if [ -n "${PARR[$i]}" ]; then
          [ -n "${PARR[$i]}" ] && eval "${PARR[$i]}=${LARR[$i]}" || eval "${PARR[$i]}=\"\""
        fi
      done
      unset icluster
      if [ -n "$tags" ]; then
        for tag in `echo -e "$tags" | tr ',' '\n'`; do
          [ `echo "$tag" | grep -c ^cluster\:` -eq 1 ] && icluster="${tag##*:}"
        done
      fi
      [ -z "$snodes" ] && snodes="none"
      for ip in `echo -e "$nic_ips" | tr ',' '\n'` ; do
        if [ -z "$icluster" ] ; then
          icluster=`grep ^$ip\| "$M_ROOT/cloud/servers.list.${CLOUD}" | cut -d'|' -f5` && break
        else
          [ `grep -c ^$icluster\| "$M_ROOT/conf/clusters.conf"` -eq 0 ] && unset icluster
        fi
      done
      
      if [ -z "$update_servers_list" ] ; then
        # icluster existence condition is needed for the case there are multiple
        # projects (cluster groups) in the same cloud.
        # Note that if you use same names for clusters in different cluster
        # groups, you'll get them mixed here.
        if [ -n "$icluster" -o -n "$all" ] ; then
          [ -n "$cluster" -a "$cluster" != "$icluster" ] && continue
          [ "X$state" != "X$status" ] && [ "X$state" != "Xall" ] && continue
          case $view in
            list)
              echo "Name: $name  State: $status  IPs: $nic_ips  Size: $be_vcpus/$be_memory/$disk_sizes  OS: $os  Nodes: ${pnode}+${snodes}  Started: $ctime"
              ;;
            table)
              echo "$name|$name|$status||$nic_ips|$icluster|$os|$be_vcpus/$be_memory/$disk_sizes|${pnode}+${snodes}|$ctime"
              ;;
            column)
              echo -e "Name: $name\nState: $status\nIPs: $nic_ips\nSize: $be_vcpus/$be_memory/$disk_sizes\nOS: $os\nNodes: ${pnode}+${snodes}\nStarted: $ctime"
              ;;
            none)
              ;;
            *)
              echo "------------------------------------------------------------------------------"
              #echo "Server ID: $id"
              echo "Server name: $name    Cluster: $icluster"
              echo "IPs: $nic_ips"
              echo "Server OS: $os  Server size: $be_vcpus/$be_memory/$disk_sizes"
              echo "Status: $status  Started: $ctime"
              echo "Nodes: primary: $pnode secondary: $snodes"
              echo
              ;;
          esac
          icount+=1
        fi
      else
        if [ -n "$icluster" ] ; then
          if [ `grep -c ^$icluster\| "$M_ROOT/conf/clusters.conf"` -ne 0 ] ; then
            key=`grep ^$icluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f2`
            echo "$nic_ip_0|$key|$pnode|$name|$icluster|$CLOUD" >> "$M_ROOT/cloud/servers.list.${CLOUD}"
          fi
        fi
      fi
      
    done
  else
    echo "No data. Run without --noupdate"
  fi
  IFS=$IFS1
}

lock_cloudops || exit 10
[ -z "$noupdate" ] && request
list_servers

[ -n "$count" ] && echo $icount

proper_exit 0 174

