#!/usr/bin/env bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/ (this is needed to fix vi syntax highlighting)

CURL=`which curl 2>/dev/null`
LYNX=`which lynx 2>/dev/null`
LINKS=`which links 2>/dev/null`
WGET=`which wget 2>/dev/null`
SSLEX=`which openssl 2>/dev/null`
TMPDIR=/tmp/m_script/cloud/rackspace
install -d $TMPDIR
CURL="$CURL -s"
V="v1.1"
source "${rpath}/../../conf/cloud.conf"
cat "${rpath}/auth.$V.json" | sed "s|RS_AUTH_USER|$RS_AUTH_USER|;s|RS_AUTH_KEY|$RS_AUTH_KEY|" > "$TMPDIR/auth.req"
$CURL -X POST -T "$TMPDIR/auth.req" -H "Content-Type: application/json" -H "Accept: application/json" "https://${RS_APIURL#https://}/$V/auth" | "${rpath}/../../lib/json2txt" > "$TMPDIR/auth.resp"
rm -f "$TMPDIR/auth.req"
[ `grep -c ^1\/auth\/token\/id "$TMPDIR/auth.resp"` -eq 1 ] || exit 1

exit 0

