#!/usr/bin/env bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
CURL=`which curl 2>/dev/null`
LYNX=`which lynx 2>/dev/null`
LINKS=`which links 2>/dev/null`
WGET=`which wget 2>/dev/null`
SSLEX=`which openssl 2>/dev/null`

CURL="$CURL -s -k"
V="v1.1"
[ -z "$CLOUD" ] && echo "CLOUD is not defined" && exit 1
source "$M_ROOT/conf/clouds/${CLOUD}.conf"
source "$M_ROOT/conf/mon.conf"
M_TEMP="$M_TEMP/cloud/rackspace"
install -d "$M_TEMP"

cat "$rpath/auth.$V.json" | sed "s|RS_AUTH_USER|$RS_AUTH_USER|;s|RS_AUTH_KEY|$RS_AUTH_KEY|" > "$M_TEMP/auth.req"
$CURL -X POST -T "$M_TEMP/auth.req" -H "Content-Type: application/json" -H "Accept: application/json" "https://${RS_APIURL#https://}/$V/auth" | "$M_ROOT/lib/json2txt" > "$M_TEMP/auth.resp"
rm -f "$M_TEMP/auth.req"
[ `grep -c ^0\/\"auth\"\/\"token\"\/\"id\" "$M_TEMP/auth.resp"` -eq 1 ] || exit 1

exit 0

