#!/bin/bash
echo "Pragma: no-cache"
echo "Expires: 0"
echo "Content-Cache: no-cache"
echo "Content-type: text/html"
echo ""

cat $1 | sed 's|{|<div class="json"><span class="json name">|g;s|"},"|</span></div></div><div class="json"><span class="json name">|g;s|},"|</div></div><div class="json"><span class="json name">|g;s|},|</div>|g;s|}|</div>|g;s|,|</div><div class="json"><span class="json name">|g;s|<div class="json"><span class="json name">"|<div class="json"><span class="json name">|g;s|"</div>|</span></div>|g;s|":"|</span><span class="json value">|g;s|":|</span>|g;'
 

