#!/bin/bash

cat $1 | sed 's|{|<div class="json"><span class="json name">|g;s|"},"|</span></div></div><div class="json"><span class="json name">|g;s|},"|</div></div><div class="json"><span class="json name">|g;s|},|</div>|g;s|}|</div>|g;s|,|</div><div class="json"><span class="json name">|g;s|<div class="json"><span class="json name">"|<div class="json"><span class="json name">|g;s|"</div>|</span></div>|g;s|":"|</span><span class="json value">|g;s|":|</span>|g;'
 

