#!/bin/bash

rcommand=${0##*/}
rpath=${0%/*}
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../")
#*/
MAILX=`which mail 2>/dev/null`

sendalert() {
  IFS1=$IFS; IFS='
'
  if [ -n "$al1" ]; then
    al='*'
  fi
  if [ -n "$al2" ]; then
    al='**'
  fi
  if [ -n "$al3" ]; then
    al='***'
  fi
  if [ -n "$al" ]; then
    for MLINE in `cat "$M_ROOT/conf/mail.alert.list" | grep -vE "^$|^#|^[[:space:]]*#"`; do
      aladdress=`echo "$MLINE" | cut -d' ' -f1`
      aldriver=`echo "$MLINE" | cut -sd' ' -f3`
      [ -z "$aldriver" ] && aldriver="mail"
      if [ "$aldriver" == "mail" ]; then
        echo -e "$message" | $MAILX -s "$al Server $HOSTNAME alert" "$aladdress" >> "$M_ROOT/monitoring.log" 2>&1
      else
        echo -e "$message" | "$M_ROOT"/lib/alert.drivers/$aldriver - $aladdress "$al Server $HOSTNAME alert" >> "$M_ROOT/monitoring.log" 2>&1
      fi
      unset aldriver aladdress
    done
  fi
}

message=`cat $1`
al1=`echo "$message" | grep '<\*>'`
al2=`echo "$message" | grep '<\*\*>'`
al3=`echo "$message" | grep '<\*\*\*>'`

sendalert

exit 0

