#!/bin/bash

# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

declare -i i
i=0
declare -a branch
declare -a index

addnode() {
  nd=$1
  [[ "$nd" =~ ^\? ]] && return 0
#echo "=== ${nd}"
  index[$i]="$nd"
  unset ndcont
  if [ $i -gt 1 ] ; then
    if [ "X${index[$i-2]}" == "X${nd#/}" ] ; then
      ndcont=${index[$i-1]}
    fi
  fi
  n=${#branch[*]}
  #echo "$i | $n  --  $ndcont"
  if [ -n "$ndcont" ] ; then
    for ((l=0; l<$n; l++)) ; do
      if [ $l -eq `expr $n - 1` ] ; then
        printf "${branch[$l]}\n"
      elif [ $l -eq `expr $n - 2` ] ; then
        printf "${branch[$l]% *} "
      else
        printf "${branch[$l]% *}_"
      fi
    done
    unset branch[$n-1]; unset branch[$n-2]
  else
    branch[$n]=$nd
    for ((l=0; l<=$n; l++)) ; do
      if [ "X${branch[$l]}" == "X${nd#/}" ] ; then
        for ((m=0; m<`expr $n - $l`; m++)) ; do unset branch[$l+$m+1] ; done
      fi
    done
  fi
  i+=1
}

( IFS='<>' ; for LINE in `cat $1` ; do echo "${LINE}" ; done ) | while read node ; do ([ "$node" != "" ] && [ "$node" != "|" ]) && addnode "$node"; done

unset branch index ndcont cont i LINE node

