#!/usr/bin/env bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


[[ $0 =~ ^\/ ]] && rroot='/'
for step in `echo ${0} | tr '/' ' '` ; do
  rlink=`readlink "${rroot}${rpath}${step}"`
  if [ -n "$rlink" ] ; then
    [[ $rlink =~ ^\/ ]] && rpath="${rlink}/" || rpath="${rpath}${rlink}/"
  else
    rpath="${rpath}${step}/"
  fi
done
rpath=${rpath%/}
rcommand=${rpath##*/}
rpath="${rroot}${rpath%/*}"
#*/ (this is needed to fix vi syntax highlighting)
source "${rpath}/../../conf/cloud.conf"
RSYNC=`which rsync 2>/dev/null`
[ -z "$RSYNC" ] && echo "Rsync utility not found, trying scp"
SCP=`which scp 2>/dev/null`
[ -n "$SCP" ] && [ -z "$RSYNC" ] && echo "Using scp"
[ -z "$SCP" ] && [ -z "$RSYNC" ] && echo "Neither rsync nor scp is found. Exiting" && exit 1
[ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
SSH=`which ssh 2>/dev/null`
[ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
[ -n "$SSHPORT" ] || SSHPORT=22
possible_options="cluster help region verbose recursive ip"
commflag=0
for s_option in "${@}"
do
  case ${s_option} in
  --*=*)
    if [ "$commflag" == "1" ] ; then
      command="$command ${s_option}"
    else
      s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`
      s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'`
    fi
    ;;
  --*)
    if [ "$commflag" == "1" ] ; then
      command="$command ${s_option}"
    else
      s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
      s_optarg='yes'
    fi
    ;;
  *=*)
    command="$command ${s_option}"
    exit 1
    ;;
  *)
    if [ "$commflag" == "1" ] ; then
      command="$command ${s_option}"
    else
      commflag=1
      command="${s_option}"
    fi
    ;;
  esac
  for option in `echo $possible_options | sed 's/,//g'`; do 
    [ "X$s_optname" == "X$option" ] && eval "$option=${s_optarg}"
  done
done
if [ "X$help" == "Xyes" ] ; then
  echo "Usage: ${0##*/} <options> <local path> <remote path>"
  echo 
  echo "Without options <local path> will be copied to all servers from servers.list's path"
  echo
  echo "Options:"
  echo
  echo "  --recursive              - recursive sync of directories, implies --delete"
  echo "  --cluster=clustername    - the command will be run on all servers"
  echo "                             from this cluster."
  echo "  --ip                     - ip for a single server operation."
  echo "  --region=region          - the command will be run on all servers"
  echo "                             from this region."
  echo "  --verbose                - shows each server details before running"
  echo "                             the command."
  exit 0
fi

[ -n "$recursive" ] && r="-r"
[ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"

IFS1=$IFS
IFS='
'
if [ "X$command" != "X" ] ; then
  from=${command%% *}
  to=${command#* }
  [ -n "$verbose" ] && echo "### Syncing $from to $to"
  for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v ^#|grep -v ^[[:space:]]*#` ; do
    IP=${server%%|*}
    if [ -n "$ip" ] ; then
      [ "X$IP" == "X$ip" ] || continue
    fi
    KEY=`echo $server | cut -d'|' -f2`
    if [ -n "$region" ] ; then
      REGION=`echo $server | cut -d'|' -f3`
      [ "X$REGION" == "X$region" ] || continue
    fi
    if [ -n "$cluster" ] ; then
      CLUSTER=`echo $server | cut -d'|' -f5`
      [ "X$CLUSTER" == "X$cluster" ] || continue
    fi
    if [ "X$verbose" == "Xyes" ] ; then
      echo
      echo "### Server: $server"
      echo
    fi
    [ -f "${rpath}/../../keys/$KEY" ] || KEY="${KEY}.pem"
    [ -f "${rpath}/../../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
    if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
      cp -up $from $to
    else
      if [ -n "$RSYNC" ] ; then
        $RSYNC ${r} -e "$SSH -i ${rpath}/../../keys/${KEY} -p $SSHPORT" "$from" "${IP}:${to}" || $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}"
      else
        $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}"
      fi
    fi
  done
fi
IFS=$IFS1

