#!/bin/bash

# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


rcommand=${0##*/}
rpath=${0%/*}
#*/ (this is needed to fix vi syntax highlighting)
MAILX=`which mail 2>/dev/null`
currtime=`date`
echo $currtime > ${rpath}/../../ebs_backup.report
echo "------------------------" >> ${rpath}/../../ebs_backup.report
echo >> ${rpath}/../../ebs_backup.report
possible_options="keep cluster ami state filter noupdate help region"
necessary_options=""
#[ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
for s_option in "${@}"
do
  found=0
  case ${s_option} in
  --*=*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'` 
    ;;
  --*)
    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
    s_optarg='yes' 
    ;;
  *=*)
    echo "Wrong syntax: options must start with a double dash"
    exit 1
    ;;
  *)
    s_param=${s_option}
    s_optname=''
    s_optarg=''
    ;;
  esac
  for option in `echo $possible_options | sed 's/,//g'`; do 
    [ "X$s_optname" == "X$option" ] && eval "$option=${s_optarg}" && found=1
  done
  [ "X$s_option" == "X$s_param" ] && found=1
  if [[ found -ne 1 ]]; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done
found=0

for option in `echo $necessary_options | sed 's/,//g'`; do
  [ "X$(eval echo \$$option)" == "X" ] && missing_options="${missing_options}, --${option}" && found=1
done
if [[ found -eq 1 ]]; then
  missing_options=${missing_options#*,}
  echo "Necessary options: ${missing_options} not found"
  exit 1
fi

if [ -n "$help" ] ; then
  case $help in 
    cluster)
      echo "Usage: --cluster=<cluster name>"
      echo "  Backups volumes belonging to this cluster only"
      echo "  (attached to instances tagged with \"cluster=<cluster name>\")"
    ;;
    ami)
      echo "Usage: --ami=<ami_id>"
      echo "  Backups volumes attached to instances with this AMI ID"
    ;;
    state)
      echo "Usage: --state=<state>"
      echo "  Backups volumes attached to instances in this state"
      echo "  e.g. --state=running"
    ;;
    noupdate)
      echo "Usage: --noupdate"
      echo "  Doesn't query AWS, uses the raw data of the previous query instead"
    ;;
    *)
      echo "Use help=option"
      echo "  Possible options are: ${possible_options}"
    ;;
  esac
  exit 0
fi

source ${rpath}/../../conf/cloud.conf
for var in EC2_TOOLS_BIN_PATH JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION EC2_AK ; do
  [ -z "`eval echo \\$\$var`" ] && echo "$var is not defined! Define it in conf/cloud.conf please." && exit 1
done
PATH="${EC2_TOOLS_BIN_PATH}:${PATH}"
export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION PATH

TMPDIR=/tmp/m_script/cloud/ec2
install -d $TMPDIR
[ -n "$noupdate" ] && noupdate="--noupdate"
[ -n "$region" ] && region="--region=$region"
[ -n "$cluster" ] && cluster="--cluster=$cluster"
[ -n "$ami" ] && ami="--ami=$ami"
[ -n "$state" ] && state="--state=$state"

${rpath}/../show_servers "$noupdate" "$region" "$cluster" "$ami" "$state" --filter=bID > $TMPDIR/volumes.list
if [ -n "$keep" ] ; then
  outdated=`date -d "$currtime - $keep days" +"%s"`
  ec2-describe-snapshots $region > $TMPDIR/snapshots.list
  for ebs in `cat $TMPDIR/volumes.list` ; do
    cat $TMPDIR/snapshots.list | grep "[[:space:]]$ebs[[:space:]]" | while read snap ; do
      snapID=`echo $snap | awk '{print $2}'`
      snaptime=`echo $snap | awk '{print $5}' | sed 's|T| |'`
      snaptime=`date -d "$snaptime" +"%s"`
      if [[ $snaptime -lt $outdated ]] ; then
        printf "Deleting snapshot $snapID created at $snaptime ... " >> ${rpath}/../../ebs_backup.report
        printf "`ec2-delete-snapshot $snapID >/dev/null` ... " >> ${rpath}/../../ebs_backup.report && echo "DONE" >> ${rpath}/../../ebs_backup.report || echo "ERROR" >> ${rpath}/../../ebs_backup.report
      fi
    done
    printf "Creating snapshot of volume $ebs ... " >> ${rpath}/../../ebs_backup.report
    printf "`ec2-create-snapshot $ebs >/dev/null` ... " >> ${rpath}/../../ebs_backup.report && echo "DONE" >> ${rpath}/../../ebs_backup.report || echo "ERROR" >> ${rpath}/../../ebs_backup.report
  done
else
  for ebs in `cat $TMPDIR/volumes.list` ; do
    printf "Creating snapshot of volume $ebs ... " >> ${rpath}/../../ebs_backup.report
    printf "`ec2-create-snapshot $ebs >/dev/null` ... " >> ${rpath}/../../ebs_backup.report && echo "DONE" >> ${rpath}/../../ebs_backup.report || echo "ERROR" >> ${rpath}/../../ebs_backup.report
  done
fi
if [ -n "$MAILX" ] ; then
  while read RLINE
  do
    if [ -n "${RLINE}" ]; then
      cat ${rpath}/../../ebs_backup.report | ${MAILX} -s "Server $(hostname -f) EBS volume backup report" ${RLINE}
    fi
  done < ${rpath}/../conf/mail.backup.list
fi
