#!/bin/bash
# Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rcommand=${0##*/}
rpath=${0%/*}
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
#*/

CURL=`which curl 2>/dev/null`
[ -z "$CURL" ] && echo "Curl not found" && exit 1
SSLEX=`which openssl 2>/dev/null`
[ -z "$SSLEX" ] && echo "openssl binary not found" && exit 1

possible_options="name log_request cloud nodeid description noreboot help wait"
necessary_options="name instanceid"
IFS1=$IFS
IFS='-'
for s_option in "$@"
do
  found=false
  s_option=${s_option/--/}
  s_optname=${s_option%%=*}
  s_optarg=${s_option##*=}
  [ "_$s_optarg" == "_$s_optname" ] && s_optarg="yes"

  for option in ${possible_options// /-} ; do
    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
  done
  
  if ! $found ; then 
    echo "Unknown option: $s_optname"
    exit 1
  fi
done
IFS=$IFS1

[ -z "$@" ] && help=yes

if [ -z "$help" ]; then
  found=0
  for option in `echo $necessary_options | sed 's/,//g'`; do
    [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options}, --${option}" && found=1
  done
  if [[ found -eq 1 ]]; then
    missing_options=${missing_options#*,}
    echo "Necessary options: $missing_options not found"
    exit 1
  fi
else
  cat << "EOF"
Usage: node save {options}

where options are:

name={name}            - name of the image (mandatory)
nodeid={instance id}   - EC2 instance ID
nodename={node name)   - M-Script node name
nodeip={ip}            - node IP address (the one from nodes.list)

  One of nodeid, nodename, nodeip is mandatory
  
noreboot<=yes>       - to save a running node (may lead to image inconsistency)
description={descr}  - description of the image, visible when 'describe images'
                       is called
cloud={cloud}        - narrows the search for the node to be saved; useful
                       when there is a possibility that nodes from different
                       clouds may have same IP or name
wait<=minutes>       - do not exit until image is ready; if value is omitted,
                       it's the default wait time 1 hour

EOF

fi

[ -n "$cloud" ] && CLOUD=$cloud
[ -z "$CLOUD" ] && echo "No cloud defined" && exit 1

source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/conf/clouds/${CLOUD}.conf"
source "$M_ROOT/lib/cloud_functions.sh"
LOG="$M_ROOT/logs/cloud.log"

M_TEMP="$M_TEMP/cloud/$CLOUD"
[ -d "$M_TEMP" ] || install -d "$M_TEMP"

CURL="$CURL -s -k"

# TODO: add this to cloud config
SignatureMethod=HmacSHA256
SignatureVersion=2
Version="2013-07-15"

qparams="${qparams}\nSignatureMethod=${SignatureMethod}\nSignatureVersion=${SignatureVersion}\nVersion=${Version}\nInstanceId=${nodeid}\nName=${name}"
[ -n "$noreboot" ] && qparams="${qparams}\nNoReboot=true"
[ -n "$description" ] && qparams="${qparams}\nDescription=${description}"

request() {
  timestamp=`date +"%Y-%m-%dT%H%%3A%M%%3A%S"`
  qparams="${qparams}\nTimestamp=${timestamp}"
  qparams=`echo -e -n "$qparams" | sort | grep -v ^$ | tr '\n' '&'`
  query=`echo -n "AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams%&}"`
  Q=`echo -ne "GET\nec2.amazonaws.com\n/\n$query"`
  signature=`echo -n "$Q" | $SSLEX dgst -binary -sha256 -hmac "$AWS_SECRET_ACCESS_KEY" | base64 | "$M_ROOT"/lib/urlencode`
  if [ "_$log_request" == "_yes" ]; then
    log "$CURL \"https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams}Signature=$signature\""
    reqres=`$CURL "https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams}Signature=$signature"`
    log "$reqres"
    echo "$reqres" | "$M_ROOT"/lib/xml2txt | grep -v ^$ > "$M_TEMP/${rcommand}.resp"
  else
    $CURL "https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams}Signature=$signature" | "$M_ROOT"/lib/xml2txt | grep -v ^$ > "$M_TEMP/${rcommand}.resp"
  fi
}

request CreateImage
reqparsed=`cat "$M_TEMP/${rcommand}.resp"`
[ `echo "$reqparsed" | wc -l` -eq 0 ] && log "file $M_TEMP/${rcommand}.resp is empty" && proper_exit 1 90
[ `echo "$reqparsed" | grep -c Error` -ne 0 ] && log "request failed with error `echo "$reqparsed" | grep Error | cut -d'|' -f2`" && proper_exit 1 91

echo "$reqparsed"

imageid=`echo "$reqparsed" | grep \"imageId\" | cut -sd'|' -f2 | tr -d '"'`

if [ -n "$wait" ]; then
  waitperiod=30
  if [ `expr $wait : ".*[^0-9]"` -ne 0 ]; then
    if [ $wait == "yes" ]; then
      timeout=3600
    fi
  else
    timeout=`expr $wait \* 60`
  fi
  cycles=`expr $timeout / $waitperiod`
  for ((i=0; i<$cycles; i++)); do
    status=`"$rpath"/find_images --image=$imageid | grep imageState | cut -sd'|' -f2 | tr -d '"'`
    if [ "_$status" == "_available" ]; then
      exit 0
    fi
    sleep $waitperiod
  done
  echo "Timeout waiting for image $imageid ready"
  proper_exit 33 153
fi


