#!/bin/bash

M_ROOT="$PWD/../.."
parent="$1"
node="$2"
IFS='
'
chunksmax=0
datasizemax=0
indexsizemax=0

print_table_2() {
  echo "<div class=\"tr\"><div class=\"td1\">${1}</div><div class=\"td2\">${2}</div></div>"
}

echo "<div style=\"display: table; width: 720px; margin-left: 60px;\">"
[ -f "$M_ROOT/standalone/MongoDB/data/${parent}.${node}.dat" ] || exit 0
declare -a index_size

for line in `cat "$M_ROOT/standalone/MongoDB/data/${parent}.${node}.dat" | grep ^index_size`; do eval $line ; done

for index in ${index_size[*]} ; do
  indexname=`echo "$index" | cut -d':' -f1`
  indexsize=`echo "$index" | cut -d':' -f2`
  indexsize=`expr $indexsize / 1024`

  csunits="KB"
  if [ ${#indexsize} -gt 3 ] ; then
    indexsize=`expr $indexsize / 1024` && csunits="MB"
  elif [ ${#indexsize} -gt 6 ] ; then
    indexsize=`expr $indexsize / 1048576` && csunits="GB"
  fi
  indexsize="$indexsize $csunits"
  print_table_2 $indexname $indexsize
done


echo "</div>"


