#!/bin/bash

M_ROOT="$PWD/../.."
source "$M_ROOT/conf/dash.conf"
source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/lib/dash_functions.sh"

publish_graph `"$M_ROOT"/graph --database=standalone/MongoDB/mongodb.sql3 --table=servers --metric=recstatsNotInMemory,recstatsPageFaults --where="hostport:${2}" --perpixel --width=750 --height=300 --padding=10 --legend=160 2>&1`
