#!/bin/bash

M_ROOT="$PWD/../.."
source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/lib/dash_functions.sh"

publish_graph `"$M_ROOT"/graph --database=standalone/ElasticSearch/elasticsearch.sql3 --table=nodes --metric=ind_size --where="hostport:${2}" --perpixel --width=750 --height=300 --padding=10 --legend=160 2>&1`
