#!/bin/bash

rpath=$(readlink -f "$BASH_SOURCE")
rcommand=${rpath##*/}
rpath=${rpath%/*}
#*/
[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
source "$M_ROOT/conf/mon.conf"
source "$M_ROOT/conf/clouds/${CLOUD}.conf"
source "$rpath/clouds.conf"
M_TEMP="$M_TEMP/cloud"

clouds=( $CLOUD `cat "$M_ROOT/conf/clusters.conf" | grep -v ^# | cut -d'|' -f12 | grep -v ^$ | sort | uniq` )
echo "blablabla" >> "$M_TEMP/servers.list"
for cloud in ${clouds[*]} ; do
  echo "blablabla" >> "$M_TEMP/$cloud/show_servers.resp.prev"
done

[ -f "$rpath/cycles.count" ] && [ -n "$API_CALLS_FREQ" ] && echo $API_CALLS_FREQ > "$rpath/cycles.count"


